import BlockIcon from "@mui/icons-material/Block";
import CheckIcon from "@mui/icons-material/Check";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import RefreshIcon from "@mui/icons-material/Refresh";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import StopCircleIcon from "@mui/icons-material/StopCircle";
import TerminalIcon from "@mui/icons-material/Terminal";
import VisibilityIcon from "@mui/icons-material/Visibility";
import VisibilityOffIcon from "@mui/icons-material/VisibilityOff";
import {
  Box,
  Button,
  FormControlLabel,
  Grid,
  Skeleton,
  Switch,
  Tooltip,
  Typography,
  useTheme,
} from "@mui/material";
import { alpha } from "@mui/material/styles";
import { AnimatePresence, motion } from "framer-motion";
import React from "react";

import ServiceDetailPanel from "./ServiceDetailPanel";

import type { Service } from "@/api";

import { linuxio, openServiceLogsStream } from "@/api";
import FrostedCard from "@/components/cards/RootCard";
import ComponentLoader from "@/components/loaders/ComponentLoader";
import { getServiceStatusColor } from "@/constants/statusColors";
import { useLogStream } from "@/hooks/useLogStream";

interface ServiceCardsViewProps {
  services: Service[];
  expanded: string | null;
  onExpand: (name: string | null) => void;
}

const detailLabelSx = {
  textTransform: "uppercase" as const,
  letterSpacing: "0.06em",
  fontSize: "0.6rem",
  color: "text.secondary",
  flexShrink: 0,
  width: 90,
  pt: 0.3,
};

const DetailRow: React.FC<{ label: string; children: React.ReactNode }> = ({
  label,
  children,
}) => (
  <Box
    sx={{
      display: "flex",
      gap: 2,
      py: 0.75,
      borderBottom: "1px solid",
      borderColor: "divider",
      "&:last-child": { borderBottom: "none" },
      alignItems: "flex-start",
    }}
  >
    <Typography variant="caption" sx={detailLabelSx}>
      {label}
    </Typography>
    <Box sx={{ flex: 1, minWidth: 0 }}>{children}</Box>
  </Box>
);

const formatTimestamp = (ts: unknown): string => {
  const ms = Number(ts ?? 0) / 1000;
  if (!ms) return "—";
  return new Date(ms).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const formatUnitFileState = (
  state: string,
): { label: string; auto: boolean } => {
  switch (state) {
    case "enabled":
      return { label: "Automatically starts", auto: true };
    case "enabled-runtime":
      return { label: "Automatically starts (runtime)", auto: true };
    case "static":
      return { label: "Statically enabled", auto: false };
    case "disabled":
      return { label: "Does not automatically start", auto: false };
    case "masked":
      return { label: "Masked (disabled)", auto: false };
    case "generated":
      return { label: "Generated by a generator", auto: false };
    default:
      return { label: state || "—", auto: false };
  }
};

const SelectedServiceDetails: React.FC<{ service: Service }> = ({
  service,
}) => {
  const statusColor = getServiceStatusColor(service.active_state);
  const { data: info, isPending } = linuxio.dbus.get_service_info.useQuery(
    service.name,
    { refetchInterval: 2000 },
  );
  const isActive = service.active_state === "active";
  const ts = isActive
    ? formatTimestamp(info?.ActiveEnterTimestamp)
    : formatTimestamp(info?.InactiveEnterTimestamp);
  const unitFileState = String(info?.UnitFileState ?? "");
  const { label: autoStartLabel, auto: autoStart } =
    formatUnitFileState(unitFileState);

  return (
    <>
      <DetailRow label="Status">
        <Box sx={{ display: "flex", flexDirection: "column", gap: 0.25 }}>
          <Typography
            variant="body2"
            fontWeight={600}
            sx={{ color: statusColor }}
          >
            {isActive ? "Running" : service.active_state}
            {service.sub_state &&
              service.sub_state !== service.active_state && (
                <Typography
                  component="span"
                  variant="body2"
                  color="text.secondary"
                  sx={{ ml: 1 }}
                >
                  ({service.sub_state})
                </Typography>
              )}
          </Typography>
          {isPending ? (
            <Skeleton width={200} height={14} />
          ) : (
            <Typography variant="caption" color="text.secondary">
              {isActive ? "Active" : "Inactive"} since {ts}
            </Typography>
          )}
        </Box>
      </DetailRow>
      <DetailRow label="Auto-start">
        {isPending ? (
          <Skeleton width={180} height={20} />
        ) : (
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
            {autoStart ? (
              <CheckIcon sx={{ fontSize: 15, color: "success.main" }} />
            ) : (
              <BlockIcon sx={{ fontSize: 15, color: "text.disabled" }} />
            )}
            <Typography variant="body2" fontWeight={500}>
              {autoStartLabel}
            </Typography>
          </Box>
        )}
      </DetailRow>
    </>
  );
};

const ServiceLogsCard: React.FC<{ service: Service }> = ({ service }) => {
  const theme = useTheme();
  const { logs, isLoading, error, liveMode, setLiveMode, logsBoxRef } =
    useLogStream({
      open: true,
      createStream: (tail) => openServiceLogsStream(service.name, tail),
    });

  return (
    <FrostedCard sx={{ p: 3 }}>
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          mb: 1.5,
        }}
      >
        <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
          <TerminalIcon fontSize="small" sx={{ color: "text.secondary" }} />
          <Typography variant="body2" fontWeight={600}>
            Service Logs
          </Typography>
        </Box>
        <Tooltip title={liveMode ? "Live streaming ON" : "Live streaming OFF"}>
          <FormControlLabel
            control={
              <Switch
                checked={liveMode}
                onChange={(_, v) => setLiveMode(v)}
                size="small"
              />
            }
            label="Live"
          />
        </Tooltip>
      </Box>
      <Box
        sx={{
          position: "relative",
          bgcolor: theme.codeBlock.background,
          color: theme.codeBlock.color,
          borderRadius: 1,
          overflow: "hidden",
        }}
      >
        {isLoading && (
          <Box
            sx={{
              position: "absolute",
              inset: 0,
              background: alpha(theme.codeBlock.background, 0.85),
              zIndex: 10,
            }}
          >
            <ComponentLoader />
          </Box>
        )}
        {error && (
          <Typography color="error" sx={{ p: 2 }}>
            {error}
          </Typography>
        )}
        <Box
          ref={logsBoxRef}
          className="custom-scrollbar"
          sx={{
            p: 2,
            overflow: "auto",
            fontFamily: "Fira Mono, monospace",
            fontSize: "0.8rem",
            whiteSpace: "pre-wrap",
            wordBreak: "break-all",
            minHeight: 120,
            maxHeight: 340,
          }}
        >
          {!isLoading &&
            !error &&
            (logs || (
              <Typography color="text.secondary" variant="caption">
                No logs available.
              </Typography>
            ))}
        </Box>
      </Box>
    </FrostedCard>
  );
};

const ServiceCardActions: React.FC<{ service: Service }> = ({ service }) => {
  const { data: info } = linuxio.dbus.get_service_info.useQuery(service.name, {
    refetchInterval: 2000,
  });

  const { mutate: startService, isPending: isStarting } =
    linuxio.dbus.start_service.useMutation();
  const { mutate: stopService, isPending: isStopping } =
    linuxio.dbus.stop_service.useMutation();
  const { mutate: restartService, isPending: isRestarting } =
    linuxio.dbus.restart_service.useMutation();
  const { mutate: reloadService, isPending: isReloading } =
    linuxio.dbus.reload_service.useMutation();
  const { mutate: enableService, isPending: isEnabling } =
    linuxio.dbus.enable_service.useMutation();
  const { mutate: disableService, isPending: isDisabling } =
    linuxio.dbus.disable_service.useMutation();
  const { mutate: maskService, isPending: isMasking } =
    linuxio.dbus.mask_service.useMutation();
  const { mutate: unmaskService, isPending: isUnmasking } =
    linuxio.dbus.unmask_service.useMutation();

  const isActive = service.active_state === "active";
  const unitFileState = String(info?.UnitFileState ?? "");
  const isEnabled =
    unitFileState === "enabled" || unitFileState === "enabled-runtime";
  const isMasked = unitFileState === "masked";
  const anyPending =
    isStarting || isStopping || isRestarting || isReloading ||
    isEnabling || isDisabling || isMasking || isUnmasking;

  return (
    <div
      style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}
      onClick={(e) => e.stopPropagation()}
    >
      {isActive ? (
        <Button size="small" variant="outlined" color="error"
          startIcon={<StopCircleIcon fontSize="small" />}
          onClick={() => stopService([service.name])} disabled={anyPending}>
          Stop
        </Button>
      ) : (
        <Button size="small" variant="outlined" color="success"
          startIcon={<PlayArrowIcon fontSize="small" />}
          onClick={() => startService([service.name])} disabled={anyPending}>
          Start
        </Button>
      )}
      <Button size="small" variant="outlined"
        startIcon={<RestartAltIcon fontSize="small" />}
        onClick={() => restartService([service.name])}
        disabled={!isActive || anyPending}>
        Restart
      </Button>
      <Button size="small" variant="outlined"
        startIcon={<RefreshIcon fontSize="small" />}
        onClick={() => reloadService([service.name])}
        disabled={!isActive || anyPending}>
        Reload
      </Button>
      {isEnabled ? (
        <Button size="small" variant="outlined"
          startIcon={<BlockIcon fontSize="small" />}
          onClick={() => disableService([service.name])}
          disabled={isMasked || anyPending}>
          Disable
        </Button>
      ) : (
        <Button size="small" variant="outlined" color="success"
          startIcon={<PlayArrowIcon fontSize="small" />}
          onClick={() => enableService([service.name])}
          disabled={isMasked || anyPending}>
          Enable
        </Button>
      )}
      {isMasked ? (
        <Button size="small" variant="outlined" color="warning"
          startIcon={<VisibilityIcon fontSize="small" />}
          onClick={() => unmaskService([service.name])} disabled={anyPending}>
          Unmask
        </Button>
      ) : (
        <Button size="small" variant="outlined"
          startIcon={<VisibilityOffIcon fontSize="small" />}
          onClick={() => maskService([service.name])} disabled={anyPending}>
          Mask
        </Button>
      )}
    </div>
  );
};

const ServiceCardsView: React.FC<ServiceCardsViewProps> = ({
  services,
  expanded,
  onExpand,
}) => {
  const theme = useTheme();
  const expandedService = services.find((s) => s.name === expanded) ?? null;

  if (services.length === 0) {
    return (
      <Box textAlign="center" py={4}>
        <Typography variant="body2" color="text.secondary">
          No services found.
        </Typography>
      </Box>
    );
  }

  return (
    <Grid container spacing={3}>
      <AnimatePresence>
        {services.map((service) =>
          expanded && expanded !== service.name ? null : (
            <Grid
              key={service.name}
              size={
                expanded === service.name
                  ? { xs: 12, md: 4, lg: 4 }
                  : { xs: 12, sm: 6, md: 4, lg: 3 }
              }
              component={motion.div}
              layout
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.2 }}
            >
              {(() => {
                const statusColor = getServiceStatusColor(service.active_state);
                const subStateColor =
                  service.sub_state === "running"
                    ? getServiceStatusColor("active")
                    : theme.palette.text.secondary;
                const isSelected = expanded === service.name;

                return (
                  <FrostedCard
                    onClick={() => onExpand(isSelected ? null : service.name)}
                    sx={{
                      p: 3,
                      display: "flex",
                      flexDirection: "column",
                      height: "100%",
                      cursor: "pointer",
                      transition:
                        "transform 0.2s, box-shadow 0.2s, border 0.3s ease-in-out, margin 0.3s ease-in-out",
                      borderBottomWidth: "2px",
                      borderBottomStyle: "solid",
                      borderBottomColor: isSelected
                        ? statusColor
                        : `color-mix(in srgb, ${statusColor}, transparent 70%)`,
                      ...(!isSelected && {
                        "&:hover": {
                          transform: "translateY(-4px)",
                          boxShadow: `0 8px 24px ${alpha(theme.palette.common.black, 0.35)}`,
                        },
                      }),
                    }}
                  >
                    {/* Header */}
                    <Box
                      sx={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "flex-start",
                        mb: 1.5,
                        gap: 1,
                      }}
                    >
                      {/* Left: name + description */}
                      <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Typography
                          variant="body2"
                          fontWeight="bold"
                          noWrap
                          sx={{ minWidth: 0 }}
                        >
                          {service.name}
                        </Typography>
                        {service.description && (
                          <Typography
                            variant="caption"
                            color="text.secondary"
                            noWrap
                            title={service.description}
                            sx={{ display: "block" }}
                          >
                            {service.description}
                          </Typography>
                        )}
                      </Box>

                      {/* Right: status dot */}
                      <Box
                        sx={{
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "flex-end",
                          gap: 1,
                          flexShrink: 0,
                        }}
                      >
                        <Box
                          component="span"
                          sx={{
                            display: "inline-block",
                            width: 8,
                            height: 8,
                            borderRadius: "50%",
                            bgcolor: statusColor,
                          }}
                        />
                      </Box>
                    </Box>

                    {/* Stat rows */}
                    <Box sx={{ flex: 1 }}>
                      <SelectedServiceDetails service={service} />
                      {isSelected && (
                        <>
                          <DetailRow label="Active">
                            <Typography
                              variant="body2"
                              fontWeight={500}
                              noWrap
                              sx={{ color: statusColor }}
                            >
                              {service.active_state}
                            </Typography>
                          </DetailRow>
                          <DetailRow label="Load">
                            <Typography
                              variant="body2"
                              fontWeight={500}
                              noWrap
                              sx={{
                                color:
                                  service.load_state === "loaded"
                                    ? "text.primary"
                                    : "text.secondary",
                              }}
                            >
                              {service.load_state}
                            </Typography>
                          </DetailRow>
                          <DetailRow label="Sub">
                            <Typography
                              variant="body2"
                              fontWeight={500}
                              noWrap
                              sx={{ color: subStateColor }}
                            >
                              {service.sub_state}
                            </Typography>
                          </DetailRow>
                          <ServiceCardActions service={service} />
                        </>
                      )}
                    </Box>
                  </FrostedCard>
                );
              })()}
            </Grid>
          ),
        )}

        {/* Detail panel */}
        {expandedService && (
          <Grid
            key="detail-panel"
            size={{ xs: 12, md: 8, lg: 8 }}
            component={motion.div}
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 40 }}
            transition={{ duration: 0.25, delay: 0.05 }}
          >
            <ServiceDetailPanel
              service={expandedService}
              onClose={() => onExpand(null)}
            />
          </Grid>
        )}

        {/* Logs card — full width below the two info cards */}
        {expandedService && (
          <Grid
            key="logs-panel"
            size={{ xs: 12 }}
            component={motion.div}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            transition={{ duration: 0.25, delay: 0.1 }}
          >
            <ServiceLogsCard
              key={expandedService.name}
              service={expandedService}
            />
          </Grid>
        )}
      </AnimatePresence>
    </Grid>
  );
};

export default ServiceCardsView;
