import BlockIcon from "@mui/icons-material/Block";
import CheckIcon from "@mui/icons-material/Check";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import RefreshIcon from "@mui/icons-material/Refresh";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import StopCircleIcon from "@mui/icons-material/StopCircle";
import TerminalIcon from "@mui/icons-material/Terminal";
import VisibilityIcon from "@mui/icons-material/Visibility";
import VisibilityOffIcon from "@mui/icons-material/VisibilityOff";
import {
  Button,
  FormControlLabel,
  Grid,
  Switch,
  Tooltip,
  useTheme,
} from "@mui/material";
import { alpha } from "@mui/material/styles";
import { AnimatePresence, motion } from "framer-motion";
import React from "react";

import ServiceDetailPanel from "./ServiceDetailPanel";

import type { Service } from "@/api";
import { linuxio, openServiceLogsStream } from "@/api";
import FrostedCard from "@/components/cards/RootCard";
import ComponentLoader from "@/components/loaders/ComponentLoader";
import { getServiceStatusColor } from "@/constants/statusColors";
import { useLogStream } from "@/hooks/useLogStream";

interface ServiceCardsViewProps {
  services: Service[];
  expanded: string | null;
  onExpand: (name: string | null) => void;
}

// Static sx objects — emotion caches these; per-card dynamic color is injected
// via the CSS variable --svc-status-color set on the card's style prop.
const cardSx = {
  p: 3,
  display: "flex",
  flexDirection: "column",
  height: "100%",
  cursor: "pointer",
  transition:
    "transform 0.2s, box-shadow 0.2s, border 0.3s ease-in-out, margin 0.3s ease-in-out",
  borderBottomWidth: "2px",
  borderBottomStyle: "solid",
  borderBottomColor:
    "color-mix(in srgb, var(--svc-status-color), transparent 70%)",
  "&:hover": {
    transform: "translateY(-4px)",
    boxShadow: "0 8px 24px rgba(0,0,0,0.35)",
  },
  "& .svc-card-details > .svc-detail-row:last-of-type": {
    borderBottom: "none",
  },
} as const;

const selectedCardSx = {
  p: 3,
  display: "flex",
  flexDirection: "column",
  height: "100%",
  cursor: "pointer",
  transition:
    "transform 0.2s, box-shadow 0.2s, border 0.3s ease-in-out, margin 0.3s ease-in-out",
  borderBottomWidth: "2px",
  borderBottomStyle: "solid",
  borderBottomColor: "var(--svc-status-color)",
  "& .svc-card-details > .svc-detail-row:last-of-type": {
    borderBottom: "none",
  },
} as const;

const DetailRow: React.FC<{
  label: string;
  children: React.ReactNode;
  noBorder?: boolean;
}> = ({ label, children, noBorder }) => (
  <div
    className="svc-detail-row"
    style={{
      display: "flex",
      padding: "1px 0",
      borderTop: noBorder ? undefined : "1px solid var(--mui-palette-divider)",
      alignItems: "flex-start",
    }}
  >
    <span
      style={{
        textTransform: "uppercase",
        letterSpacing: "0.06em",
        fontSize: "0.6rem",
        color: "var(--mui-palette-text-secondary)",
        flexShrink: 0,
        width: 90,
        paddingTop: 3,
      }}
    >
      {label}
    </span>
    <div style={{ flex: 1, minWidth: 0 }}>{children}</div>
  </div>
);

const formatTimestamp = (ts: unknown): string => {
  const ms = Number(ts ?? 0) / 1000;
  if (!ms) return "—";
  return new Date(ms).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const formatUnitFileState = (
  state: string,
): { label: string; auto: boolean } => {
  switch (state) {
    case "enabled":
      return { label: "Automatically starts", auto: true };
    case "enabled-runtime":
      return { label: "Automatically starts (runtime)", auto: true };
    case "static":
      return { label: "Statically enabled", auto: false };
    case "disabled":
      return { label: "Does not automatically start", auto: false };
    case "masked":
      return { label: "Masked (disabled)", auto: false };
    case "generated":
      return { label: "Generated by a generator", auto: false };
    default:
      return { label: state || "—", auto: false };
  }
};

const SelectedServiceDetails = React.memo<{ service: Service }>(
  ({ service }) => {
    const statusColor = getServiceStatusColor(service.active_state);
    const isActive = service.active_state === "active";
    const ts = isActive
      ? formatTimestamp(service.active_enter_timestamp)
      : formatTimestamp(service.inactive_enter_timestamp);
    const { label: autoStartLabel, auto: autoStart } = formatUnitFileState(
      service.unit_file_state,
    );

    return (
      <>
        <DetailRow label="Status" noBorder>
          <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
            <span
              style={{
                fontSize: "0.85rem",
                fontWeight: 600,
                color: statusColor,
              }}
            >
              {isActive ? "Running" : service.active_state}
              {service.sub_state &&
                service.sub_state !== service.active_state && (
                  <span
                    style={{
                      color: "var(--mui-palette-text-secondary)",
                      marginLeft: 8,
                      fontWeight: 400,
                    }}
                  >
                    ({service.sub_state})
                  </span>
                )}
            </span>
            <span
              style={{
                fontSize: "0.7rem",
                color: "var(--mui-palette-text-secondary)",
              }}
            >
              {isActive ? "Active" : "Inactive"} since {ts}
            </span>
          </div>
        </DetailRow>
        <DetailRow label="Auto-start">
          <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
            {autoStart ? (
              <CheckIcon
                style={{
                  fontSize: 15,
                  color: "var(--mui-palette-success-main)",
                }}
              />
            ) : (
              <BlockIcon
                style={{
                  fontSize: 15,
                  color: "var(--mui-palette-text-disabled)",
                }}
              />
            )}
            <span style={{ fontSize: "0.75rem", fontWeight: 500 }}>
              {autoStartLabel}
            </span>
          </div>
        </DetailRow>
      </>
    );
  },
);
SelectedServiceDetails.displayName = "SelectedServiceDetails";

const ServiceLogsCard: React.FC<{ service: Service }> = ({ service }) => {
  const theme = useTheme();
  const { logs, isLoading, error, liveMode, setLiveMode, logsBoxRef } =
    useLogStream({
      open: true,
      createStream: (tail) => openServiceLogsStream(service.name, tail),
    });

  return (
    <FrostedCard sx={{ p: 3 }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 12,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <TerminalIcon
            fontSize="small"
            style={{ color: "var(--mui-palette-text-secondary)" }}
          />
          <span style={{ fontSize: "0.875rem", fontWeight: 600 }}>
            Service Logs
          </span>
        </div>
        <Tooltip title={liveMode ? "Live streaming ON" : "Live streaming OFF"}>
          <FormControlLabel
            control={
              <Switch
                checked={liveMode}
                onChange={(_, v) => setLiveMode(v)}
                size="small"
              />
            }
            label="Live"
          />
        </Tooltip>
      </div>
      <div
        style={{
          position: "relative",
          backgroundColor: theme.codeBlock.background,
          color: theme.codeBlock.color,
          borderRadius: 4,
          overflow: "hidden",
        }}
      >
        {isLoading && (
          <div
            style={{
              position: "absolute",
              inset: 0,
              background: alpha(theme.codeBlock.background, 0.85),
              zIndex: 10,
            }}
          >
            <ComponentLoader />
          </div>
        )}
        {error && (
          <div style={{ color: "var(--mui-palette-error-main)", padding: 16 }}>
            {error}
          </div>
        )}
        <div
          ref={logsBoxRef}
          className="custom-scrollbar"
          style={{
            padding: 16,
            overflow: "auto",
            fontFamily: "Fira Mono, monospace",
            fontSize: "0.8rem",
            whiteSpace: "pre-wrap",
            wordBreak: "break-all",
            minHeight: 120,
            maxHeight: 340,
          }}
        >
          {!isLoading &&
            !error &&
            (logs || (
              <span
                style={{
                  color: "var(--mui-palette-text-secondary)",
                  fontSize: "0.75rem",
                }}
              >
                No logs available.
              </span>
            ))}
        </div>
      </div>
    </FrostedCard>
  );
};

const ServiceCardActions: React.FC<{ service: Service }> = ({ service }) => {
  const { data: info } = linuxio.dbus.get_service_info.useQuery(service.name, {
    refetchInterval: 2000,
  });

  const { mutate: startService, isPending: isStarting } =
    linuxio.dbus.start_service.useMutation();
  const { mutate: stopService, isPending: isStopping } =
    linuxio.dbus.stop_service.useMutation();
  const { mutate: restartService, isPending: isRestarting } =
    linuxio.dbus.restart_service.useMutation();
  const { mutate: reloadService, isPending: isReloading } =
    linuxio.dbus.reload_service.useMutation();
  const { mutate: enableService, isPending: isEnabling } =
    linuxio.dbus.enable_service.useMutation();
  const { mutate: disableService, isPending: isDisabling } =
    linuxio.dbus.disable_service.useMutation();
  const { mutate: maskService, isPending: isMasking } =
    linuxio.dbus.mask_service.useMutation();
  const { mutate: unmaskService, isPending: isUnmasking } =
    linuxio.dbus.unmask_service.useMutation();

  const isActive = service.active_state === "active";
  const unitFileState = String(info?.UnitFileState ?? "");
  const isEnabled =
    unitFileState === "enabled" || unitFileState === "enabled-runtime";
  const isMasked = unitFileState === "masked";
  const anyPending =
    isStarting ||
    isStopping ||
    isRestarting ||
    isReloading ||
    isEnabling ||
    isDisabling ||
    isMasking ||
    isUnmasking;

  return (
    <div
      style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}
      onClick={(e) => e.stopPropagation()}
    >
      {isActive ? (
        <Button
          size="small"
          variant="outlined"
          color="error"
          startIcon={<StopCircleIcon fontSize="small" />}
          onClick={() => stopService([service.name])}
          disabled={anyPending}
        >
          Stop
        </Button>
      ) : (
        <Button
          size="small"
          variant="outlined"
          color="success"
          startIcon={<PlayArrowIcon fontSize="small" />}
          onClick={() => startService([service.name])}
          disabled={anyPending}
        >
          Start
        </Button>
      )}
      <Button
        size="small"
        variant="outlined"
        startIcon={<RestartAltIcon fontSize="small" />}
        onClick={() => restartService([service.name])}
        disabled={!isActive || anyPending}
      >
        Restart
      </Button>
      <Button
        size="small"
        variant="outlined"
        startIcon={<RefreshIcon fontSize="small" />}
        onClick={() => reloadService([service.name])}
        disabled={!isActive || anyPending}
      >
        Reload
      </Button>
      {isEnabled ? (
        <Button
          size="small"
          variant="outlined"
          startIcon={<BlockIcon fontSize="small" />}
          onClick={() => disableService([service.name])}
          disabled={isMasked || anyPending}
        >
          Disable
        </Button>
      ) : (
        <Button
          size="small"
          variant="outlined"
          color="success"
          startIcon={<PlayArrowIcon fontSize="small" />}
          onClick={() => enableService([service.name])}
          disabled={isMasked || anyPending}
        >
          Enable
        </Button>
      )}
      {isMasked ? (
        <Button
          size="small"
          variant="outlined"
          color="warning"
          startIcon={<VisibilityIcon fontSize="small" />}
          onClick={() => unmaskService([service.name])}
          disabled={anyPending}
        >
          Unmask
        </Button>
      ) : (
        <Button
          size="small"
          variant="outlined"
          startIcon={<VisibilityOffIcon fontSize="small" />}
          onClick={() => maskService([service.name])}
          disabled={anyPending}
        >
          Mask
        </Button>
      )}
    </div>
  );
};

// Memoized so unchanged services skip re-render on each 2s poll
const ServiceCard = React.memo<{
  service: Service;
  isSelected: boolean;
  onExpand: (name: string | null) => void;
}>(({ service, isSelected, onExpand }) => {
  const statusColor = getServiceStatusColor(service.active_state);
  const subStateColor =
    service.sub_state === "running"
      ? getServiceStatusColor("active")
      : "var(--mui-palette-text-secondary)";

  return (
    <FrostedCard
      onClick={() => onExpand(isSelected ? null : service.name)}
      style={{ "--svc-status-color": statusColor } as React.CSSProperties}
      sx={isSelected ? selectedCardSx : cardSx}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          marginBottom: 12,
          gap: 8,
        }}
      >
        <div style={{ flex: 1, minWidth: 0 }}>
          <div
            style={{
              fontSize: "0.875rem",
              fontWeight: "bold",
              whiteSpace: "nowrap",
              overflow: "hidden",
              textOverflow: "ellipsis",
            }}
          >
            {service.name}
          </div>
          {service.description && (
            <div
              style={{
                fontSize: "0.7rem",
                color: "var(--mui-palette-text-secondary)",
                whiteSpace: "nowrap",
                overflow: "hidden",
                textOverflow: "ellipsis",
              }}
              title={service.description}
            >
              {service.description}
            </div>
          )}
        </div>
        <span
          style={{
            display: "inline-block",
            width: 8,
            height: 8,
            borderRadius: "50%",
            backgroundColor: statusColor,
            flexShrink: 0,
            marginTop: 4,
          }}
        />
      </div>

      {/* Stat rows */}
      <div style={{ flex: 1 }} className="svc-card-details">
        <SelectedServiceDetails service={service} />
        {isSelected && (
          <>
            <DetailRow label="Active">
              <span
                style={{
                  fontSize: "0.75rem",
                  fontWeight: 500,
                  color: statusColor,
                }}
              >
                {service.active_state}
              </span>
            </DetailRow>
            <DetailRow label="Load">
              <span
                style={{
                  fontSize: "0.75rem",
                  fontWeight: 500,
                  color:
                    service.load_state === "loaded"
                      ? "var(--mui-palette-text-primary)"
                      : "var(--mui-palette-text-secondary)",
                }}
              >
                {service.load_state}
              </span>
            </DetailRow>
            <DetailRow label="Sub">
              <span
                style={{
                  fontSize: "0.75rem",
                  fontWeight: 500,
                  color: subStateColor,
                }}
              >
                {service.sub_state}
              </span>
            </DetailRow>
            <ServiceCardActions service={service} />
          </>
        )}
      </div>
    </FrostedCard>
  );
});
ServiceCard.displayName = "ServiceCard";

const ServiceCardsView: React.FC<ServiceCardsViewProps> = ({
  services,
  expanded,
  onExpand,
}) => {
  const expandedService = services.find((s) => s.name === expanded) ?? null;

  if (services.length === 0) {
    return (
      <div style={{ textAlign: "center", padding: "32px 0" }}>
        <span
          style={{
            fontSize: "0.875rem",
            color: "var(--mui-palette-text-secondary)",
          }}
        >
          No services found.
        </span>
      </div>
    );
  }

  return (
    <Grid container spacing={3}>
      <AnimatePresence>
        {services.map((service) =>
          expanded && expanded !== service.name ? null : (
            <Grid
              key={service.name}
              size={
                expanded === service.name
                  ? { xs: 12, md: 4, lg: 4 }
                  : { xs: 12, sm: 6, md: 4, lg: 3 }
              }
              component={motion.div}
              layout
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.2 }}
            >
              <ServiceCard
                service={service}
                isSelected={expanded === service.name}
                onExpand={onExpand}
              />
            </Grid>
          ),
        )}

        {expandedService && (
          <Grid
            key="detail-panel"
            size={{ xs: 12, md: 8, lg: 8 }}
            component={motion.div}
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 40 }}
            transition={{ duration: 0.25, delay: 0.05 }}
          >
            <ServiceDetailPanel
              service={expandedService}
              onClose={() => onExpand(null)}
            />
          </Grid>
        )}

        {expandedService && (
          <Grid
            key="logs-panel"
            size={{ xs: 12 }}
            component={motion.div}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            transition={{ duration: 0.25, delay: 0.1 }}
          >
            <ServiceLogsCard
              key={expandedService.name}
              service={expandedService}
            />
          </Grid>
        )}
      </AnimatePresence>
    </Grid>
  );
};

export default ServiceCardsView;
