import BlockIcon from "@mui/icons-material/Block";
import CheckIcon from "@mui/icons-material/Check";
import CloseIcon from "@mui/icons-material/Close";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import RestartAltIcon from "@mui/icons-material/RestartAlt";
import StopCircleIcon from "@mui/icons-material/StopCircle";
import TerminalIcon from "@mui/icons-material/Terminal";
import {
  Box,
  Button,
  Collapse,
  Divider,
  FormControlLabel,
  IconButton,
  Skeleton,
  Switch,
  Tooltip,
  Typography,
} from "@mui/material";
import { alpha, useTheme } from "@mui/material/styles";
import React, { useState } from "react";

import type { Service } from "./ServiceTable";

import { linuxio, openServiceLogsStream } from "@/api";
import FrostedCard from "@/components/cards/RootCard";
import ComponentLoader from "@/components/loaders/ComponentLoader";
import { getServiceStatusColor } from "@/constants/statusColors";
import { useLogStream } from "@/hooks/useLogStream";

interface ServiceDetailPanelProps {
  service: Service;
  onClose: () => void;
  onRestart: (service: Service) => void;
  onStop: (service: Service) => void;
  onStart: (service: Service) => void;
  isLoading: boolean;
}

const labelSx = {
  textTransform: "uppercase" as const,
  letterSpacing: "0.06em",
  fontSize: "0.6rem",
  color: "text.secondary",
  flexShrink: 0,
  width: 90,
  pt: 0.3,
};

const Row: React.FC<{ label: string; children: React.ReactNode }> = ({
  label,
  children,
}) => (
  <Box
    sx={{
      display: "flex",
      gap: 2,
      py: 0.75,
      borderBottom: "1px solid",
      borderColor: "divider",
      "&:last-child": { borderBottom: "none" },
      alignItems: "flex-start",
    }}
  >
    <Typography variant="caption" sx={labelSx}>
      {label}
    </Typography>
    <Box sx={{ flex: 1, minWidth: 0 }}>{children}</Box>
  </Box>
);

const formatTimestamp = (ts: unknown): string => {
  const ms = Number(ts ?? 0) / 1000;
  if (!ms) return "—";
  return new Date(ms).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const formatBytes = (val: unknown): string => {
  const b = Number(val ?? 0);
  if (!b || b > 1e18) return "—"; // uint64 max = not available
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} kB`;
  if (b < 1024 * 1024 * 1024) return `${(b / (1024 * 1024)).toFixed(1)} MB`;
  return `${(b / (1024 * 1024 * 1024)).toFixed(2)} GB`;
};

const formatUnitFileState = (
  state: string,
): { label: string; auto: boolean } => {
  switch (state) {
    case "enabled":
      return { label: "Automatically starts", auto: true };
    case "enabled-runtime":
      return { label: "Automatically starts (runtime)", auto: true };
    case "static":
      return { label: "Statically enabled", auto: false };
    case "disabled":
      return { label: "Does not automatically start", auto: false };
    case "masked":
      return { label: "Masked (disabled)", auto: false };
    case "generated":
      return { label: "Generated by a generator", auto: false };
    default:
      return { label: state || "—", auto: false };
  }
};

const toStringArray = (val: unknown): string[] => {
  if (!Array.isArray(val)) return [];
  return val.filter((v): v is string => typeof v === "string" && v.length > 0);
};

const DEP_FIELDS: Array<{ label: string; key: string }> = [
  { label: "Requires", key: "Requires" },
  { label: "Wants", key: "Wants" },
  { label: "Wanted by", key: "WantedBy" },
  { label: "Triggered by", key: "TriggeredBy" },
  { label: "Part of", key: "PartOf" },
  { label: "Conflicts", key: "Conflicts" },
  { label: "Before", key: "Before" },
  { label: "After", key: "After" },
];

const ServiceDetailPanel: React.FC<ServiceDetailPanelProps> = ({
  service,
  onClose,
  onRestart,
  onStop,
  onStart,
  isLoading: actionLoading,
}) => {
  const theme = useTheme();
  const statusColor = getServiceStatusColor(service.active_state);
  const [showLogs, setShowLogs] = useState(false);

  const { data: info, isPending } = linuxio.dbus.get_service_info.useQuery(
    service.name,
    { refetchInterval: 2000 },
  );

  const {
    logs,
    isLoading: logsLoading,
    error: logsError,
    liveMode,
    setLiveMode,
    logsBoxRef,
    resetState: resetLogs,
  } = useLogStream({
    open: showLogs,
    createStream: (tail) => openServiceLogsStream(service.name, tail),
  });

  const handleToggleLogs = () => {
    if (showLogs) resetLogs();
    setShowLogs((v) => !v);
  };

  const unitFileState = String(info?.UnitFileState ?? "");
  const { label: autoStartLabel, auto: autoStart } =
    formatUnitFileState(unitFileState);
  const fragmentPath = String(info?.FragmentPath ?? "");
  const mainPid = Number(info?.MainPID ?? 0);
  const isActive = service.active_state === "active";
  const ts = isActive
    ? formatTimestamp(info?.ActiveEnterTimestamp)
    : formatTimestamp(info?.InactiveEnterTimestamp);
  const memory = formatBytes(info?.MemoryCurrent);

  return (
    <FrostedCard sx={{ p: 3 }}>
      {/* Header */}
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          mb: 2.5,
        }}
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "flex-start",
            gap: 1,
            minWidth: 0,
          }}
        >
          <Box
            sx={{
              width: 10,
              height: 10,
              borderRadius: "50%",
              bgcolor: statusColor,
              flexShrink: 0,
              mt: 0.8,
            }}
          />
          <Box sx={{ minWidth: 0 }}>
            <Typography variant="h6" fontWeight="bold" noWrap>
              {service.name}
            </Typography>
            {service.description && (
              <Typography variant="body2" color="text.secondary">
                {service.description}
              </Typography>
            )}
          </Box>
        </Box>
        <IconButton
          onClick={onClose}
          size="small"
          sx={{ ml: 1, flexShrink: 0 }}
        >
          <CloseIcon fontSize="small" />
        </IconButton>
      </Box>

      <Divider sx={{ mb: 2 }} />

      {/* Info rows */}
      <Box>
        <Row label="Status">
          <Box sx={{ display: "flex", flexDirection: "column", gap: 0.25 }}>
            <Typography
              variant="body2"
              fontWeight={600}
              sx={{ color: statusColor }}
            >
              {isActive ? "Running" : service.active_state}
              {service.sub_state &&
                service.sub_state !== service.active_state && (
                  <Typography
                    component="span"
                    variant="body2"
                    color="text.secondary"
                    sx={{ ml: 1 }}
                  >
                    ({service.sub_state})
                  </Typography>
                )}
            </Typography>
            {isPending ? (
              <Skeleton width={200} height={14} />
            ) : (
              <Typography variant="caption" color="text.secondary">
                {isActive ? "Active" : "Inactive"} since {ts}
              </Typography>
            )}
          </Box>
        </Row>

        <Row label="Auto-start">
          {isPending ? (
            <Skeleton width={180} height={20} />
          ) : (
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
              {autoStart ? (
                <CheckIcon sx={{ fontSize: 15, color: "success.main" }} />
              ) : (
                <BlockIcon sx={{ fontSize: 15, color: "text.disabled" }} />
              )}
              <Typography variant="body2" fontWeight={500}>
                {autoStartLabel}
              </Typography>
            </Box>
          )}
        </Row>

        {mainPid > 0 && (
          <Row label="PID">
            <Typography variant="body2" fontWeight={500}>
              {mainPid}
            </Typography>
          </Row>
        )}

        {memory !== "—" && (
          <Row label="Memory">
            <Typography variant="body2" fontWeight={500}>
              {memory}
            </Typography>
          </Row>
        )}

        <Row label="Path">
          {isPending ? (
            <Skeleton width="80%" height={20} />
          ) : (
            <Typography
              variant="body2"
              fontWeight={500}
              sx={{
                wordBreak: "break-all",
                fontFamily: "monospace",
                fontSize: "0.8rem",
              }}
            >
              {fragmentPath || "—"}
            </Typography>
          )}
        </Row>

        <Row label="Load">
          <Typography variant="body2" fontWeight={500}>
            {service.load_state}
          </Typography>
        </Row>

        {/* Dependency rows — only when non-empty */}
        {!isPending &&
          DEP_FIELDS.map(({ label, key }) => {
            const items = toStringArray(info?.[key]);
            if (!items.length) return null;
            return (
              <Row key={key} label={label}>
                <Typography
                  variant="body2"
                  fontWeight={500}
                  sx={{ wordBreak: "break-word" }}
                >
                  {items.join(", ")}
                </Typography>
              </Row>
            );
          })}
      </Box>

      <Divider sx={{ my: 2 }} />

      {/* Actions + live toggle */}
      <Box
        sx={{
          display: "flex",
          gap: 1,
          flexWrap: "wrap",
          alignItems: "center",
        }}
      >
        <Button
          size="small"
          variant={showLogs ? "contained" : "outlined"}
          startIcon={<TerminalIcon fontSize="small" />}
          onClick={handleToggleLogs}
        >
          Service Logs
        </Button>
        {isActive ? (
          <>
            <Button
              size="small"
              variant="outlined"
              startIcon={<RestartAltIcon fontSize="small" />}
              onClick={() => onRestart(service)}
              disabled={actionLoading}
            >
              Restart
            </Button>
            <Button
              size="small"
              variant="outlined"
              color="error"
              startIcon={<StopCircleIcon fontSize="small" />}
              onClick={() => onStop(service)}
              disabled={actionLoading}
            >
              Stop
            </Button>
          </>
        ) : (
          <Button
            size="small"
            variant="outlined"
            color="success"
            startIcon={<PlayArrowIcon fontSize="small" />}
            onClick={() => onStart(service)}
            disabled={actionLoading}
          >
            Start
          </Button>
        )}
        {showLogs && (
          <Tooltip
            title={liveMode ? "Live streaming ON" : "Live streaming OFF"}
          >
            <FormControlLabel
              control={
                <Switch
                  checked={liveMode}
                  onChange={(_, v) => setLiveMode(v)}
                  size="small"
                />
              }
              label="Live"
              sx={{ ml: "auto" }}
            />
          </Tooltip>
        )}
      </Box>

      {/* Inline log viewer */}
      <Collapse in={showLogs} unmountOnExit>
        <Box
          sx={{
            mt: 2,
            position: "relative",
            bgcolor: theme.codeBlock.background,
            color: theme.codeBlock.color,
            borderRadius: 1,
            overflow: "hidden",
          }}
        >
          {logsLoading && (
            <Box
              sx={{
                position: "absolute",
                inset: 0,
                background: alpha(theme.codeBlock.background, 0.85),
                zIndex: 10,
              }}
            >
              <ComponentLoader />
            </Box>
          )}
          {logsError && (
            <Typography color="error" sx={{ p: 2 }}>
              {logsError}
            </Typography>
          )}
          <Box
            ref={logsBoxRef}
            className="custom-scrollbar"
            sx={{
              p: 2,
              overflow: "auto",
              fontFamily: "Fira Mono, monospace",
              fontSize: "0.8rem",
              whiteSpace: "pre-wrap",
              wordBreak: "break-all",
              minHeight: 120,
              maxHeight: 340,
            }}
          >
            {!logsLoading &&
              !logsError &&
              (logs || (
                <Typography color="text.secondary" variant="caption">
                  No logs available.
                </Typography>
              ))}
          </Box>
        </Box>
      </Collapse>
    </FrostedCard>
  );
};

export default ServiceDetailPanel;
