import { Icon } from "@iconify/react";
import { useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import React from "react";

import type { UnitInfo } from "@/api";
import type { UnitListItem } from "@/components/cards/UnitCard";

import { linuxio } from "@/api";
import UnitCard from "@/components/cards/UnitCard";
import { DetailRow } from "@/components/cards/UnitInfoPanelCard";
import UnifiedCollapsibleTable, {
  UnifiedTableColumn,
} from "@/components/tables/UnifiedCollapsibleTable";
import AppButton from "@/components/ui/AppButton";
import AppCircularProgress from "@/components/ui/AppCircularProgress";
import AppGrid from "@/components/ui/AppGrid";
import AppTooltip from "@/components/ui/AppTooltip";
import StatusDot from "@/components/ui/StatusDot";
import { getServiceStatusColor } from "@/constants/statusColors";
import { useScopedToast } from "@/hooks/useScopedToast";
import { useAppMediaQuery, useAppTheme } from "@/theme";
import { getMutationErrorMessage } from "@/utils/mutations";

export type { UnitListItem } from "@/components/cards/UnitCard";
export { DetailRow } from "@/components/cards/UnitInfoPanelCard";
export type { UnitInfoRow } from "@/components/cards/UnitInfoPanelCard";
export { UnitInfoPanel } from "@/components/cards/UnitInfoPanelCard";

interface UnitTableViewProps<T> {
  data: T[];
  desktopColumns: UnifiedTableColumn[];
  emptyMessage: string;
  getRowKey: (row: T, index: number) => string | number;
  mobileColumns: UnifiedTableColumn[];
  onDoubleClick?: (key: string | number) => void;
  onSelect?: (key: string | number | null) => void;
  renderMainRow: (row: T, isMobile: boolean, index: number) => React.ReactNode;
  renderMobileExpandedContent?: (row: T, index: number) => React.ReactNode;
  selected?: string | number | null;
}

interface UnitCardsViewProps<T extends UnitListItem> {
  emptyMessage: string;
  expanded: string | null;
  items: T[];
  onExpand: (name: string | null) => void;
  renderActions?: (item: T) => React.ReactNode;
  renderBottomPanel?: (item: T) => React.ReactNode;
  renderDetailPanel: (item: T) => React.ReactNode;
  renderSelectedRows?: (item: T) => React.ReactNode;
  renderSummaryRows: (item: T) => React.ReactNode;
}

export function statusDot(activeState: string) {
  return (
    <StatusDot
      color={getServiceStatusColor(activeState)}
      style={{ marginRight: 8 }}
    />
  );
}

export function formatBytes(val: unknown): string {
  const b = Number(val ?? 0);
  if (!b || b > 1e18) return "—";
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} kB`;
  if (b < 1024 * 1024 * 1024) return `${(b / (1024 * 1024)).toFixed(1)} MB`;
  return `${(b / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

export function formatTimestamp(ts: unknown): string {
  const ms = Number(ts ?? 0) / 1000;
  if (!ms) return "—";
  return new Date(ms).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function formatUsec(usec: unknown): string {
  const n = Number(usec ?? 0);
  if (!n || !Number.isFinite(n) || n >= Number.MAX_SAFE_INTEGER) return "—";
  const d = new Date(n / 1000);
  return Number.isNaN(d.getTime()) ? "—" : d.toLocaleString();
}

export function formatUnitFileState(state: string): {
  label: string;
  auto: boolean;
} {
  switch (state) {
    case "enabled":
      return { label: "Automatically starts", auto: true };
    case "enabled-runtime":
      return { label: "Automatically starts (runtime)", auto: true };
    case "static":
      return { label: "Statically enabled", auto: false };
    case "disabled":
      return { label: "Does not automatically start", auto: false };
    case "masked":
      return { label: "Masked (disabled)", auto: false };
    case "generated":
      return { label: "Generated by a generator", auto: false };
    default:
      return { label: state || "—", auto: false };
  }
}

export function AutoStartRow({ unitFileState }: { unitFileState: string }) {
  const { label, auto } = formatUnitFileState(unitFileState);

  return (
    <DetailRow label="Auto-start">
      <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
        {auto ? (
          <Icon
            color="var(--app-palette-success-main)"
            height={15}
            icon="mdi:check"
            width={15}
          />
        ) : (
          <Icon
            color="var(--app-palette-text-disabled)"
            height={15}
            icon="mdi:block-helper"
            width={15}
          />
        )}
        <span style={{ fontSize: "0.75rem", fontWeight: 500 }}>{label}</span>
      </div>
    </DetailRow>
  );
}

interface UnitStatusRowsProps {
  activeEnterTimestamp?: number;
  activeLabel?: string;
  activeState: string;
  inactiveEnterTimestamp?: number;
  subState: string;
  unitFileState: string;
}

export function UnitStatusRows({
  activeState,
  subState,
  unitFileState,
  activeEnterTimestamp,
  inactiveEnterTimestamp,
  activeLabel,
}: UnitStatusRowsProps) {
  const statusColor = getServiceStatusColor(activeState);
  const isActive = activeState === "active";
  const timestamp = formatTimestamp(
    isActive ? activeEnterTimestamp : inactiveEnterTimestamp,
  );

  return (
    <>
      <DetailRow label="Status" noBorder>
        <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
          <span
            style={{
              fontSize: "0.85rem",
              fontWeight: 600,
              color: statusColor,
            }}
          >
            {isActive ? (activeLabel ?? activeState) : activeState}
            {subState && subState !== activeState && (
              <span
                style={{
                  color: "var(--app-palette-text-secondary)",
                  marginLeft: 8,
                  fontWeight: 400,
                }}
              >
                ({subState})
              </span>
            )}
          </span>
          {timestamp !== "—" && (
            <span
              style={{
                fontSize: "0.7rem",
                color: "var(--app-palette-text-secondary)",
              }}
            >
              {isActive ? "Active" : "Inactive"} since {timestamp}
            </span>
          )}
        </div>
      </DetailRow>
      <AutoStartRow unitFileState={unitFileState} />
    </>
  );
}

const buttonIcon = (pending: boolean, iconName: string) =>
  pending ? (
    <AppCircularProgress color="inherit" size={16} />
  ) : (
    <Icon height={16} icon={iconName} width={16} />
  );

export const UnitCardActions: React.FC<{
  unitName: string;
  activeState: string;
  unitFileState: string;
  info: UnitInfo | undefined;
}> = ({ unitName, activeState, unitFileState, info }) => {
  const toast = useScopedToast({ href: "/services", label: "Open services" });
  const queryClient = useQueryClient();

  const invalidateUnit = React.useCallback(() => {
    queryClient.invalidateQueries({
      queryKey: linuxio.systemd.list_services.queryKey(),
    });
    queryClient.invalidateQueries({
      queryKey: linuxio.systemd.get_unit_info.queryKey(unitName),
    });
  }, [queryClient, unitName]);

  const makeHandlers = React.useCallback(
    (verb: string) => ({
      onSuccess: () => {
        toast.success(`${unitName} ${verb}`);
        invalidateUnit();
      },
      onError: (err: Error) =>
        toast.error(
          getMutationErrorMessage(err, `Failed to ${verb} ${unitName}`),
        ),
    }),
    [unitName, invalidateUnit, toast],
  );

  const { mutate: startService, isPending: isStarting } =
    linuxio.systemd.start_service.useMutation(makeHandlers("started"));
  const { mutate: stopService, isPending: isStopping } =
    linuxio.systemd.stop_service.useMutation(makeHandlers("stopped"));
  const { mutate: restartService, isPending: isRestarting } =
    linuxio.systemd.restart_service.useMutation(makeHandlers("restarted"));
  const { mutate: reloadService, isPending: isReloading } =
    linuxio.systemd.reload_service.useMutation(makeHandlers("reloaded"));
  const { mutate: enableService, isPending: isEnabling } =
    linuxio.systemd.enable_service.useMutation(makeHandlers("enabled"));
  const { mutate: disableService, isPending: isDisabling } =
    linuxio.systemd.disable_service.useMutation(makeHandlers("disabled"));
  const { mutate: maskService, isPending: isMasking } =
    linuxio.systemd.mask_service.useMutation(makeHandlers("masked"));
  const { mutate: unmaskService, isPending: isUnmasking } =
    linuxio.systemd.unmask_service.useMutation(makeHandlers("unmasked"));
  const { mutate: resetFailedService, isPending: isResettingFailed } =
    linuxio.systemd.reset_failed_service.useMutation(makeHandlers("reset"));

  const isActive = activeState === "active";
  const isFailed = activeState === "failed";
  const liveUnitFileState = String(info?.UnitFileState ?? unitFileState ?? "");
  const isEnabled =
    liveUnitFileState === "enabled" || liveUnitFileState === "enabled-runtime";
  const isMasked = liveUnitFileState === "masked";
  const anyPending =
    isStarting ||
    isStopping ||
    isRestarting ||
    isReloading ||
    isEnabling ||
    isDisabling ||
    isMasking ||
    isUnmasking ||
    isResettingFailed;

  return (
    <div
      onClick={(e) => e.stopPropagation()}
      style={{
        display: "flex",
        gap: 6,
        flexWrap: "nowrap",
        marginTop: 12,
        minWidth: 0,
      }}
    >
      {isActive ? (
        <AppTooltip title="Stop">
          <AppButton
            color="error"
            disabled={anyPending}
            onClick={() => stopService([unitName])}
            size="small"
            startIcon={buttonIcon(isStopping, "mdi:stop-circle")}
            variant="outlined"
          >
            Stop
          </AppButton>
        </AppTooltip>
      ) : (
        <AppTooltip title="Start">
          <AppButton
            color="success"
            disabled={anyPending}
            onClick={() => startService([unitName])}
            size="small"
            startIcon={buttonIcon(isStarting, "mdi:play")}
            variant="outlined"
          >
            Start
          </AppButton>
        </AppTooltip>
      )}
      <AppTooltip title="Restart (stop then start)">
        <span>
          <AppButton
            disabled={!isActive || anyPending}
            onClick={() => restartService([unitName])}
            size="small"
            startIcon={buttonIcon(isRestarting, "mdi:restart")}
            variant="outlined"
          >
            Restart
          </AppButton>
        </span>
      </AppTooltip>
      <AppTooltip title="Reload configuration without restarting (if supported)">
        <span>
          <AppButton
            disabled={!isActive || anyPending}
            onClick={() => reloadService([unitName])}
            size="small"
            startIcon={buttonIcon(isReloading, "mdi:refresh")}
            variant="outlined"
          >
            Reload
          </AppButton>
        </span>
      </AppTooltip>
      {isEnabled ? (
        <AppTooltip title="Disable autostart at boot">
          <span>
            <AppButton
              disabled={isMasked || anyPending}
              onClick={() => disableService([unitName])}
              size="small"
              startIcon={buttonIcon(isDisabling, "mdi:block-helper")}
              variant="outlined"
            >
              Disable
            </AppButton>
          </span>
        </AppTooltip>
      ) : (
        <AppTooltip title="Enable autostart at boot">
          <span>
            <AppButton
              color="success"
              disabled={isMasked || anyPending}
              onClick={() => enableService([unitName])}
              size="small"
              startIcon={buttonIcon(isEnabling, "mdi:play")}
              variant="outlined"
            >
              Enable
            </AppButton>
          </span>
        </AppTooltip>
      )}
      {isMasked ? (
        <AppTooltip title="Unmask to allow the unit to be started">
          <AppButton
            color="warning"
            disabled={anyPending}
            onClick={() => unmaskService([unitName])}
            size="small"
            startIcon={buttonIcon(isUnmasking, "mdi:eye")}
            variant="outlined"
          >
            Unmask
          </AppButton>
        </AppTooltip>
      ) : (
        <AppTooltip title="Mask to completely prevent the unit from starting">
          <AppButton
            disabled={anyPending}
            onClick={() => maskService([unitName])}
            size="small"
            startIcon={buttonIcon(isMasking, "mdi:eye-off")}
            variant="outlined"
          >
            Mask
          </AppButton>
        </AppTooltip>
      )}
      {isFailed && (
        <AppTooltip title="Clear the failed state so the unit can be started again">
          <AppButton
            color="warning"
            disabled={anyPending}
            onClick={() => resetFailedService([unitName])}
            size="small"
            startIcon={buttonIcon(isResettingFailed, "mdi:broom")}
            variant="outlined"
          >
            Reset
          </AppButton>
        </AppTooltip>
      )}
    </div>
  );
};

export function UnitTableView<T>({
  data,
  desktopColumns,
  mobileColumns,
  getRowKey,
  renderMainRow,
  renderMobileExpandedContent,
  selected,
  onSelect,
  onDoubleClick,
  emptyMessage,
}: UnitTableViewProps<T>) {
  const theme = useAppTheme();
  const isMobile = useAppMediaQuery(theme.breakpoints.down("sm"));

  return (
    <UnifiedCollapsibleTable
      columns={isMobile ? mobileColumns : desktopColumns}
      data={data}
      emptyMessage={emptyMessage}
      getRowKey={getRowKey}
      onRowClick={
        isMobile
          ? undefined
          : (row, index) => {
              const rowKey = getRowKey(row, index);
              onSelect?.(selected === rowKey ? null : rowKey);
            }
      }
      onRowDoubleClick={(row, index) => onDoubleClick?.(getRowKey(row, index))}
      renderExpandedContent={
        isMobile && renderMobileExpandedContent
          ? (row, index) => renderMobileExpandedContent(row, index)
          : undefined
      }
      renderMainRow={(row, index) => renderMainRow(row, isMobile, index)}
      selectedKey={selected}
    />
  );
}

export function UnitCardsView<T extends UnitListItem>({
  items,
  expanded,
  onExpand,
  renderSummaryRows,
  renderSelectedRows,
  renderActions,
  renderDetailPanel,
  renderBottomPanel,
  emptyMessage,
}: UnitCardsViewProps<T>) {
  const theme = useAppTheme();
  const isCompactLayout = useAppMediaQuery(theme.breakpoints.down("md"));
  const expandedItem = items.find((item) => item.name === expanded) ?? null;

  if (items.length === 0) {
    return (
      <div style={{ textAlign: "center", padding: "32px 0" }}>
        <span
          style={{
            fontSize: "0.875rem",
            color: "var(--app-palette-text-secondary)",
          }}
        >
          {emptyMessage}
        </span>
      </div>
    );
  }

  if (!expandedItem) {
    return (
      <AppGrid container spacing={3}>
        {items.map((item) => (
          <AppGrid key={item.name} size={{ xs: 12, sm: 6, md: 4, lg: 3 }}>
            <UnitCard
              isSelected={false}
              item={item}
              onExpand={onExpand}
              renderSummaryRows={renderSummaryRows}
            />
          </AppGrid>
        ))}
      </AppGrid>
    );
  }

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: theme.spacing(3),
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: isCompactLayout ? "column" : "row",
          alignItems: "stretch",
          gap: theme.spacing(2.5),
        }}
      >
        <div
          style={{
            flex: isCompactLayout ? "0 0 auto" : 1,
            width: isCompactLayout ? "100%" : undefined,
            display: "flex",
          }}
        >
          <UnitCard
            isSelected={true}
            item={expandedItem}
            onExpand={onExpand}
            renderActions={renderActions}
            renderSelectedRows={renderSelectedRows}
            renderSummaryRows={renderSummaryRows}
          />
        </div>
        <motion.div
          animate={{ opacity: 1, x: 0, y: 0 }}
          initial={{
            opacity: 0,
            x: isCompactLayout ? 0 : 40,
            y: isCompactLayout ? 20 : 0,
          }}
          style={{
            width: isCompactLayout ? "100%" : "33.33%",
            flexShrink: 0,
            display: "flex",
          }}
          transition={{ duration: 0.25, delay: 0.05 }}
        >
          {renderDetailPanel(expandedItem)}
        </motion.div>
      </div>
      {renderBottomPanel && (
        <motion.div
          animate={{ opacity: 1, y: 0 }}
          initial={{ opacity: 0, y: 20 }}
          transition={{ duration: 0.25, delay: 0.1 }}
        >
          {renderBottomPanel(expandedItem)}
        </motion.div>
      )}
    </div>
  );
}
