package api

import "github.com/mordilloSan/LinuxIO/backend/bridge/apischema"

var routes = apischema.NewRouteCatalog()

var ClearIconCache = routes.Job("docker.clear_icon_cache", apischema.NoRequest(), apischema.TypeOf[apischema.MessageResponse]())
var Compose = routes.Runner("docker.compose", apischema.TypeOf[apischema.DockerComposeRequest](), apischema.TypeOf[apischema.JobSnapshot]())
var ComposeDown = routes.Job("docker.compose_down", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.TypeOf[any]())
var ComposeRestart = routes.Job("docker.compose_restart", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.TypeOf[any]())
var ComposeStop = routes.Job("docker.compose_stop", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.TypeOf[any]())
var ComposeUp = routes.Job("docker.compose_up", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.TypeOf[any]())
var ConnectToProxy = routes.Job("docker.connect_to_proxy", apischema.TypeOf[apischema.ContainerIDRequest](), apischema.TypeOf[apischema.MessageResponse]())
var CreateNetwork = routes.Job("docker.create_network", apischema.TypeOf[apischema.NameRequest](), apischema.NoResponse())
var CreateVolume = routes.Job("docker.create_volume", apischema.TypeOf[apischema.NameRequest](), apischema.NoResponse())
var DeleteComposeStack = routes.Job("docker.delete_compose_stack", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.NoResponse(), apischema.NoEndpoint())
var DeleteImage = routes.Job("docker.delete_image", apischema.TypeOf[apischema.ImageIDRequest](), apischema.NoResponse())
var DeleteNetwork = routes.Job("docker.delete_network", apischema.TypeOf[apischema.IDRequest](), apischema.NoResponse())
var DeleteStack = routes.Job("docker.delete_stack", apischema.TypeOf[apischema.DeleteStackRequest](), apischema.TypeOf[apischema.DeleteStackResult]())
var DeleteVolume = routes.Job("docker.delete_volume", apischema.TypeOf[apischema.NameRequest](), apischema.NoResponse())
var DisableCaddy = routes.Job("docker.disable_caddy", apischema.NoRequest(), apischema.TypeOf[apischema.MessageResponse]())
var EnableCaddy = routes.Job("docker.enable_caddy", apischema.NoRequest(), apischema.TypeOf[apischema.MessageResponse]())
var GetCaddyStatus = routes.Query("docker.get_caddy_status", apischema.NoRequest(), apischema.TypeOf[apischema.CaddyStatusResponse]())
var GetComposeFilePath = routes.Query("docker.get_compose_file_path", apischema.TypeOf[apischema.StackNameRequest](), apischema.TypeOf[apischema.ComposeFilePathResponse]())
var GetComposeProject = routes.Query("docker.get_compose_project", apischema.TypeOf[apischema.ProjectNameRequest](), apischema.TypeOf[apischema.ComposeProject]())
var GetDockerFolders = routes.Query("docker.get_docker_folders", apischema.NoRequest(), apischema.TypeOf[apischema.DockerFoldersResponse]())
var GetDockerInfo = routes.Query("docker.get_docker_info", apischema.NoRequest(), apischema.TypeOf[apischema.DockerSystemInfo]())
var GetIcon = routes.Query("docker.get_icon", apischema.TypeOf[apischema.IdentifierRequest](), apischema.TypeOf[apischema.DockerIconDataResponse]())
var GetIconInfo = routes.Query("docker.get_icon_info", apischema.TypeOf[apischema.IdentifierRequest](), apischema.TypeOf[apischema.DockerIconInfoResponse]())
var GetIconURI = routes.Query("docker.get_icon_uri", apischema.TypeOf[apischema.IdentifierRequest](), apischema.TypeOf[apischema.DockerIconURIResponse]())
var Indexer = routes.Runner("docker.indexer", apischema.NoRequest(), apischema.TypeOf[apischema.JobSnapshot]())
var ListAutoUpdateContainers = routes.Query("docker.list_auto_update_containers", apischema.NoRequest(), apischema.TypeOf[[]string]())
var ListComposeProjects = routes.Query("docker.list_compose_projects", apischema.NoRequest(), apischema.TypeOf[[]apischema.ComposeProject]())
var ListContainers = routes.Query("docker.list_containers", apischema.NoRequest(), apischema.TypeOf[[]apischema.ContainerInfo]())
var ListImages = routes.Query("docker.list_images", apischema.NoRequest(), apischema.TypeOf[[]apischema.DockerImage]())
var ListNetworks = routes.Query("docker.list_networks", apischema.NoRequest(), apischema.TypeOf[[]apischema.DockerNetwork]())
var ListVolumes = routes.Query("docker.list_volumes", apischema.NoRequest(), apischema.TypeOf[[]apischema.DockerVolume]())
var LogsFollow = routes.Runner("docker.logs.follow", apischema.TypeOf[apischema.DockerLogsFollowRequest](), apischema.NoResponse(), apischema.NoEndpoint())
var NormalizeCompose = routes.Query("docker.normalize_compose", apischema.TypeOf[apischema.ContentRequest](), apischema.NoResponse(), apischema.NoEndpoint())
var ReindexDockerFolders = routes.Job("docker.reindex_docker_folders", apischema.NoRequest(), apischema.NoResponse(), apischema.NoEndpoint())
var ReloadCaddy = routes.Job("docker.reload_caddy", apischema.NoRequest(), apischema.TypeOf[apischema.MessageResponse]())
var RemoveContainer = routes.Job("docker.remove_container", apischema.TypeOf[apischema.ContainerIDRequest](), apischema.NoResponse())
var RestartContainer = routes.Job("docker.restart_container", apischema.TypeOf[apischema.ContainerIDRequest](), apischema.NoResponse())
var SetAutoUpdate = routes.Job("docker.set_auto_update", apischema.TypeOf[apischema.DockerSetAutoUpdateRequest](), apischema.TypeOf[apischema.MessageResponse]())
var StartAllStopped = routes.Job("docker.start_all_stopped", apischema.NoRequest(), apischema.TypeOf[apischema.DockerStartedFailedResponse]())
var StartContainer = routes.Job("docker.start_container", apischema.TypeOf[apischema.ContainerIDRequest](), apischema.NoResponse())
var StopAllRunning = routes.Job("docker.stop_all_running", apischema.NoRequest(), apischema.TypeOf[apischema.DockerStoppedFailedResponse]())
var StopContainer = routes.Job("docker.stop_container", apischema.TypeOf[apischema.ContainerIDRequest](), apischema.NoResponse())
var SystemPrune = routes.Job("docker.system_prune", apischema.TypeOf[apischema.DockerSystemPruneRequest](), apischema.TypeOf[apischema.DockerSystemPruneResponse]())
var ValidateCompose = routes.Query("docker.validate_compose", apischema.TypeOf[apischema.ContentRequest](), apischema.TypeOf[apischema.ValidateComposeResponse]())
var ValidateStackDirectory = routes.Query("docker.validate_stack_directory", apischema.TypeOf[apischema.DirPathRequest](), apischema.TypeOf[apischema.DirectoryValidationResult]())

var Routes = routes.All()
