export function formatBytes(val: unknown): string {
  const b = Number(val ?? 0);
  if (!b || b > 1e18) return "—";
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} kB`;
  if (b < 1024 * 1024 * 1024) return `${(b / (1024 * 1024)).toFixed(1)} MB`;
  return `${(b / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

export function formatTimestamp(ts: unknown): string {
  const ms = Number(ts ?? 0) / 1000;
  if (!ms) return "—";
  return new Date(ms).toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function formatUsec(usec: unknown): string {
  const n = Number(usec ?? 0);
  if (!n || !Number.isFinite(n) || n >= Number.MAX_SAFE_INTEGER) return "—";
  const d = new Date(n / 1000);
  return Number.isNaN(d.getTime()) ? "—" : d.toLocaleString();
}

export function formatUnitFileState(state: string): {
  label: string;
  auto: boolean;
} {
  switch (state) {
    case "enabled":
      return { label: "Automatically starts", auto: true };
    case "enabled-runtime":
      return { label: "Automatically starts (runtime)", auto: true };
    case "static":
      return { label: "Statically enabled", auto: false };
    case "disabled":
      return { label: "Does not automatically start", auto: false };
    case "masked":
      return { label: "Masked (disabled)", auto: false };
    case "generated":
      return { label: "Generated by a generator", auto: false };
    default:
      return { label: state || "—", auto: false };
  }
}
