server:
  port: 80
  baseURL: /navigator/
  logging:
    - levels: "info|warning|error|debug"
      apiLevels: "{{API_LEVELS}}"
      noColors: false
      output: stdout
      utc: true
  sources:
    - path: /server
      config:
        defaultEnabled: true
        conditionals:
          hidden: false
          ignoreZeroSizeFolders: false
          rules:
            - folderPath: "/proc"
            - folderPath: "/sys"
            - folderPath: "/dev"
            - folderPath: "/var/lib/docker"
  database: /home/filebrowser/data/database.db
frontend:
  disableDefaultLinks: true
  styling:
    customCSS: "custom.css"
auth:
  methods:
    proxy:
      enabled: true
      header: "{{SECRET_KEY}}"
      createUser: true
    password:
      enabled: false
userDefaults:
  editorQuickSave: true
  hideSidebarFileActions: true
  disableQuickToggles: true
  stickySidebar: false
  showHidden: true
  dateFormat: true
  gallerySize: 0
  quickDownload: false
  lockPassword: true
  disableSettings: true
  permissions:
    api: true
    admin: true
    modify: true
    share: false
    realtime: true
  loginMethod: "proxy"
  disableUpdateNotifications: true
