server:
  port: 80
  baseURL: /navigator/
  logging:
    - levels: "info|warning|error|debug"
      apiLevels: disabled
      output: stdout
      utc: true
  sources:
    - path: /server
      config:
        defaultEnabled: true
        exclude:
          hidden: false
          ignoreZeroSizeFolders: false
          folderPaths:
            - /proc
            - /sys
            - /dev
            - /var/lib/docker/overlay2
  database: /home/filebrowser/data/database.db
auth:
  methods:
    proxy:
      enabled: true
      header: "{{SECRET_KEY}}"
      createUser: false
    password:
      enabled: false
frontend:
  name: ""
  disableDefaultLinks: true
  externalLinks:
    - text: "FileBrowser Quantum" # the text to display on the link  validate:required
      url: "https://github.com/gtsteffaniak/filebrowser/releases/" # the url to link to  validate:required~
  styling:
    customCSS: "custom.css"
userDefaults:
  permissions:
    api: true
    admin: true
    modify: true
    share: false
    realtime: true
