server:
  port: 80
  baseURL: /navigator/
  logging:
    - levels: "info|warning|error|debug"
      apiLevels: disabled
      output: stdout
      utc: true
  sources:
    - path: /server
      config:
        defaultEnabled: true
        exclude:
          hidden: false
          ignoreZeroSizeFolders: false
          folderPaths:
            - /proc
            - /sys
            - /dev
            - /var/lib/docker/overlay2
  database: /home/filebrowser/data/database.db
auth:
  methods:
    proxy:
      enabled: true
      header: "{{SECRET_KEY}}"
      createUser: true
    password:
      enabled: false
frontend:
  disableDefaultLinks: true
  disableUsedPercentage: true
  styling:
    customCSS: "custom.css"
userDefaults:
  editorQuickSave: false
  hideSidebarFileActions: true
  disableQuickToggles: true
  disableSearchOptions: false
  stickySidebar: false
  darkMode: true
  locale: "en"
  viewMode: "normal"
  singleClick: false
  showHidden: true
  dateFormat: true
  themeColor: "var(--blue)"
  quickDownload: false
  lockPassword: true
  disableSettings: true
  permissions:
    api: true
    admin: true
    modify: true
    share: false
    realtime: true
  loginMethod: "proxy"
  disableUpdateNotifications: true
  deleteWithoutConfirming: false
