//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/goccy/go-yaml"

	"github.com/mordilloSan/LinuxIO/backend/bridge/internal/config"
)

// stripHeader drops the leading contiguous run of `#`-prefixed lines and a
// single following blank line, returning the YAML body. It tolerates files
// without a header (returns input unchanged) and files using either LF or CRLF.
func stripHeader(b []byte) []byte {
	i := 0
	for i < len(b) {
		if b[i] != '#' {
			break
		}
		nl := bytes.IndexByte(b[i:], '\n')
		if nl < 0 {
			return nil
		}
		i += nl + 1
	}
	if i < len(b) && b[i] == '\r' {
		i++
	}
	if i < len(b) && b[i] == '\n' {
		i++
	}
	return b[i:]
}

func gitVersion() string {
	// Try exact tag first, then branch name
	if out, err := exec.Command("git", "describe", "--tags", "--exact-match").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			return v
		}
	}
	if out, err := exec.Command("git", "rev-parse", "--abbrev-ref", "HEAD").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			return v
		}
	}
	return "unknown"
}

func main() {
	out := filepath.FromSlash("config_generated.yaml")

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		log.Fatalf("mkdir: %v", err)
	}

	data, err := yaml.Marshal(config.ExampleDefaults())
	if err != nil {
		log.Fatalf("marshal: %v", err)
	}

	if existing, err := os.ReadFile(out); err == nil {
		if bytes.Equal(stripHeader(existing), data) {
			log.Printf("%s unchanged, skipping write", out)
			return
		}
	}

	now := time.Now().Format("15:04:05 02/01/2006")
	version := gitVersion()
	header := fmt.Sprintf("# Auto-generated by generator.go — do not edit directly.\n# Generated at %s\n# Version %s\n\n", now, version)

	if err := os.WriteFile(out, append([]byte(header), data...), 0o644); err != nil {
		log.Fatalf("write: %v", err)
	}
}
