export type RouteMode = "query" | "job" | "duplex";

export const ROUTE_MODES = {
  "jobs.get": "query",
  "jobs.list": "query",
  "jobs.cancel": "job",
  "jobs.attach": "duplex",
  "jobs.data": "duplex",
  "jobs.events": "duplex",

  "packages.update": "job",

  "system.get_capabilities": "query",
  "system.get_cpu_info": "query",
  "system.get_sensor_info": "query",
  "system.get_motherboard_info": "query",
  "system.get_memory_info": "query",
  "system.get_host_info": "query",
  "system.get_uptime": "query",
  "system.get_fs_info": "query",
  "system.get_processes": "query",
  "system.get_services": "query",
  "system.get_gpu_info": "query",
  "system.get_updates_fast": "query",
  "system.get_network_info": "query",
  "system.get_disk_throughput": "query",
  "system.get_system_info": "query",
  "system.get_pci_devices": "query",
  "system.get_memory_modules": "query",
  "system.get_health_summary": "query",
  "system.list_failed_login_events": "query",
  "system.dismiss_unclean_shutdown": "job",
  "system.dismiss_failed_login_alert": "job",
  "system.get_server_time": "query",
  "system.get_timezones": "query",

  "docker.get_docker_info": "query",
  "docker.compose": "job",
  "docker.indexer": "job",
  "docker.list_containers": "query",
  "docker.start_container": "job",
  "docker.stop_container": "job",
  "docker.remove_container": "job",
  "docker.restart_container": "job",
  "docker.list_images": "query",
  "docker.delete_image": "job",
  "docker.list_networks": "query",
  "docker.create_network": "job",
  "docker.delete_network": "job",
  "docker.list_volumes": "query",
  "docker.create_volume": "job",
  "docker.delete_volume": "job",
  "docker.list_compose_projects": "query",
  "docker.get_compose_project": "query",
  "docker.compose_up": "job",
  "docker.compose_down": "job",
  "docker.compose_stop": "job",
  "docker.compose_restart": "job",
  "docker.delete_stack": "job",
  "docker.get_docker_folders": "query",
  "docker.validate_compose": "query",
  "docker.normalize_compose": "query",
  "docker.get_compose_file_path": "query",
  "docker.validate_stack_directory": "query",
  "docker.reindex_docker_folders": "job",
  "docker.delete_compose_stack": "job",
  "docker.get_icon_uri": "query",
  "docker.get_icon": "query",
  "docker.get_icon_info": "query",
  "docker.clear_icon_cache": "job",
  "docker.start_all_stopped": "job",
  "docker.stop_all_running": "job",
  "docker.list_auto_update_containers": "query",
  "docker.set_auto_update": "job",
  "docker.get_caddy_status": "query",
  "docker.enable_caddy": "job",
  "docker.disable_caddy": "job",
  "docker.reload_caddy": "job",
  "docker.connect_to_proxy": "job",
  "docker.system_prune": "job",
  "docker.logs.follow": "job",

  "dbus.reboot": "job",
  "dbus.power_off": "job",
  "dbus.logoff": "job",
  "dbus.get_updates_basic": "query",
  "dbus.get_update_detail": "query",
  "dbus.install_package": "job",
  "dbus.get_auto_updates": "query",
  "dbus.set_auto_updates": "job",
  "dbus.apply_offline_updates": "job",
  "dbus.get_update_history": "query",
  "dbus.list_timers": "query",
  "dbus.list_sockets": "query",
  "dbus.list_services": "query",
  "dbus.get_unit_info": "query",
  "dbus.start_service": "job",
  "dbus.stop_service": "job",
  "dbus.restart_service": "job",
  "dbus.reload_service": "job",
  "dbus.enable_service": "job",
  "dbus.disable_service": "job",
  "dbus.mask_service": "job",
  "dbus.unmask_service": "job",
  "dbus.reset_failed_service": "job",
  "dbus.get_network_info": "query",
  "dbus.set_ipv4_manual": "job",
  "dbus.set_ipv4": "job",
  "dbus.set_ipv6": "job",
  "dbus.set_mtu": "job",
  "dbus.enable_connection": "job",
  "dbus.disable_connection": "job",
  "dbus.set_hostname": "job",
  "dbus.get_ntp_status": "query",
  "dbus.set_ntp": "job",
  "dbus.set_server_time": "job",
  "dbus.get_timezone": "query",
  "dbus.set_timezone": "job",
  "dbus.get_ntp_servers": "query",
  "dbus.set_ntp_servers": "job",

  "filebrowser.resource_get": "query",
  "filebrowser.resource_stat": "query",
  "filebrowser.resource_delete": "job",
  "filebrowser.resource_post": "job",
  "filebrowser.resource_patch": "job",
  "filebrowser.compress": "job",
  "filebrowser.extract": "job",
  "filebrowser.copy": "job",
  "filebrowser.move": "job",
  "filebrowser.index": "job",
  "filebrowser.upload": "job",
  "filebrowser.download": "job",
  "filebrowser.archive": "job",
  "filebrowser.chmod": "job",
  "filebrowser.dir_size": "query",
  "filebrowser.indexer_status": "query",
  "filebrowser.subfolders": "query",
  "filebrowser.search": "query",
  "filebrowser.users_groups": "query",

  "config.get": "query",
  "config.set": "job",
  "indexer.get_config": "query",
  "indexer.get_status": "query",
  "indexer.set_config": "job",
  "control.version": "query",
  "control.app_update": "job",

  "power.get_status": "query",
  "power.start": "job",
  "power.set_profile": "job",
  "power.disable": "job",

  "wireguard.list_interfaces": "query",
  "wireguard.add_interface": "job",
  "wireguard.remove_interface": "job",
  "wireguard.list_peers": "query",
  "wireguard.add_peer": "job",
  "wireguard.remove_peer": "job",
  "wireguard.peer_qrcode": "query",
  "wireguard.peer_config_download": "query",
  "wireguard.up_interface": "job",
  "wireguard.down_interface": "job",
  "wireguard.enable_interface": "job",
  "wireguard.disable_interface": "job",

  "terminal.list_shells": "query",
  "terminal.open": "duplex",
  "container.open": "duplex",

  "accounts.list_users": "query",
  "accounts.get_user_details": "query",
  "accounts.list_user_logins": "query",
  "accounts.terminate_session": "job",
  "accounts.create_user": "job",
  "accounts.delete_user": "job",
  "accounts.modify_user": "job",
  "accounts.change_password": "job",
  "accounts.lock_user": "job",
  "accounts.unlock_user": "job",
  "accounts.list_groups": "query",
  "accounts.create_group": "job",
  "accounts.delete_group": "job",
  "accounts.modify_group_members": "job",
  "accounts.list_shells": "query",

  "shares.list_nfs_shares": "query",
  "shares.create_nfs_share": "job",
  "shares.update_nfs_share": "job",
  "shares.delete_nfs_share": "job",
  "shares.list_samba_shares": "query",
  "shares.create_samba_share": "job",
  "shares.update_samba_share": "job",
  "shares.delete_samba_share": "job",

  "storage.list_pvs": "query",
  "storage.list_vgs": "query",
  "storage.list_lvs": "query",
  "storage.create_lv": "job",
  "storage.delete_lv": "job",
  "storage.resize_lv": "job",
  "storage.list_nfs_mounts": "query",
  "storage.list_nfs_exports": "query",
  "storage.mount_nfs": "job",
  "storage.unmount_nfs": "job",
  "storage.remount_nfs": "job",
  "storage.unmount_filesystem": "job",
  "storage.create_btrfs_subvolume": "job",
  "storage.get_drive_info": "query",
  "storage.run_smart_test": "job",
  "logs.general.follow": "job",
  "logs.service.follow": "job",
} as const satisfies Record<string, RouteMode>;

export function routeName(handler: string, command: string): string {
  return `${handler}.${command}`;
}

export function getRouteMode(route: string): RouteMode | undefined {
  return ROUTE_MODES[route as keyof typeof ROUTE_MODES];
}
