/**
 * Extracts only the specific Iconify icons used in this app and writes them
 * to src/lib/icons.ts so they are bundled at build time — no CDN calls needed.
 *
 * Run: node scripts/generate-icons.mjs
 * Called automatically by the build and analyze npm scripts.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(__dirname, "..");

function loadIconSet(name) {
  const jsonPath = resolve(
    frontendDir,
    `node_modules/@iconify-json/${name}/icons.json`,
  );
  return JSON.parse(readFileSync(jsonPath, "utf-8"));
}

function extractIcons(data, names) {
  const result = {};
  for (const name of names) {
    const icon = data.icons[name];
    if (icon) {
      result[name] = icon;
    } else {
      console.warn(`  ⚠️  Icon not found: ${data.prefix}:${name}`);
    }
  }
  return result;
}

// Every Iconify icon string used in the app (excluding dynamic ones like
// simple-icons:${platform} which can't be known at build time).
const ICONS = {
  mdi: [
    "ethernet",
    "docker",
    "harddisk",
    "harddisk-plus",
    "pencil",
    "play",
    "stop",
    "restart",
    "delete",
    "delete-outline",
    "file-document-outline",
    "console",
    "text-box-outline",
    "wifi",
    "lan-connect",
    "network",
  ],
  ph: ["cpu"],
  la: ["memory"],
  bi: ["motherboard", "gpu-card"],
};

let output = `// Auto-generated by scripts/generate-icons.mjs — do not edit manually.
// Re-generated automatically on every build via the prebuild npm script.
// Only the specific icons used by the app are included — no full icon sets.
import { addCollection } from "@iconify/react";

`;

for (const [prefix, names] of Object.entries(ICONS)) {
  console.log(`Processing ${prefix}: ${names.join(", ")}`);
  const data = loadIconSet(prefix);
  const icons = extractIcons(data, names);
  const count = Object.keys(icons).length;

  output += `// ${prefix} — ${count} icon${count !== 1 ? "s" : ""}
addCollection({
  prefix: ${JSON.stringify(prefix)},
  width: ${data.width ?? 24},
  height: ${data.height ?? 24},
  icons: ${JSON.stringify(icons, null, 2)},
});

`;
}

mkdirSync(resolve(frontendDir, "src/lib"), { recursive: true });
const outPath = resolve(frontendDir, "src/lib/icons.ts");
writeFileSync(outPath, output);
console.log(`✅ Icon bundle written to src/lib/icons.ts`);
