package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/mordilloSan/LinuxIO/backend/bridge/apischema"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}
	outDir := filepath.Join(repoRoot, "frontend", "src", "api", "generated")
	if mkdirErr := os.MkdirAll(outDir, 0o755); mkdirErr != nil {
		fatal(mkdirErr)
	}

	modelsPath := filepath.Join(repoRoot, "frontend", "src", "api", "linuxio-models.ts")
	modelNames, err := exportedModelNames(modelsPath)
	if err != nil {
		fatal(err)
	}

	if routeErr := writeFile(filepath.Join(outDir, "route-metadata.ts"), renderRouteMetadata()); routeErr != nil {
		fatal(routeErr)
	}
	if typesErr := writeFile(filepath.Join(outDir, "linuxio-types.ts"), renderTypes(modelNames)); typesErr != nil {
		fatal(typesErr)
	}
	if clientErr := writeFile(filepath.Join(outDir, "client.ts"), renderClient()); clientErr != nil {
		fatal(clientErr)
	}
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, statErr := os.Stat(filepath.Join(dir, "frontend", "src", "api")); statErr == nil {
			return dir, nil
		}
		if parent := filepath.Dir(dir); parent == dir {
			return "", fmt.Errorf("could not find repo root from %s", wd)
		}
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "linuxio-api-gen:", err)
	os.Exit(1)
}

func writeFile(path string, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func header() string {
	return "// Code generated by linuxio-api-gen; DO NOT EDIT.\n\n"
}

func renderRouteMetadata() string {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString("export type RouteMode = \"query\" | \"job\" | \"duplex\";\n\n")
	b.WriteString("export const ROUTE_MODES = {\n")
	for _, route := range apischema.Routes {
		fmt.Fprintf(&b, "  %q: %q,\n", route.Route, string(route.Mode))
	}
	b.WriteString("} as const satisfies Record<string, RouteMode>;\n\n")
	b.WriteString("export function routeName(handler: string, command: string): string {\n")
	b.WriteString("  return `${handler}.${command}`;\n")
	b.WriteString("}\n\n")
	b.WriteString("export function getRouteMode(route: string): RouteMode | undefined {\n")
	b.WriteString("  return ROUTE_MODES[route as keyof typeof ROUTE_MODES];\n")
	b.WriteString("}\n")
	return b.String()
}

func renderTypes(modelNames []string) string {
	var b strings.Builder
	b.WriteString(header())
	usedModels := usedModelNames(modelNames)
	if len(usedModels) > 0 {
		b.WriteString("import type {\n")
		for _, name := range usedModels {
			fmt.Fprintf(&b, "  %s,\n", name)
		}
		b.WriteString("} from \"../linuxio-models\";\n")
	}
	b.WriteString("export type * from \"../linuxio-models\";\n\n")
	b.WriteString("export interface LinuxIOSchema {\n")
	byHandler := routesByHandler()
	handlers := sortedKeys(byHandler)
	for _, handler := range handlers {
		if !hasEndpoint(byHandler[handler]) {
			continue
		}
		fmt.Fprintf(&b, "  %s: {\n", handler)
		for _, route := range byHandler[handler] {
			if !route.Endpoint() {
				continue
			}
			fmt.Fprintf(&b, "    %s: { args: %s; result: %s };\n", route.Command(), route.ArgsTS, route.ResultTS)
		}
		b.WriteString("  };\n\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("/** Extract handler names from schema */\n")
	b.WriteString("export type HandlerName = keyof LinuxIOSchema;\n\n")
	b.WriteString("/** Extract command names for a given handler */\n")
	b.WriteString("export type CommandName<H extends HandlerName> = keyof LinuxIOSchema[H];\n\n")
	b.WriteString("/** Extract args type for a handler/command pair */\n")
	b.WriteString("export type CommandArgs<\n")
	b.WriteString("  H extends HandlerName,\n")
	b.WriteString("  C extends CommandName<H>,\n")
	b.WriteString("> = LinuxIOSchema[H][C] extends { args: infer A }\n")
	b.WriteString("  ? A extends unknown[]\n")
	b.WriteString("    ? A\n")
	b.WriteString("    : never\n")
	b.WriteString("  : never;\n\n")
	b.WriteString("/** Extract result type for a handler/command pair */\n")
	b.WriteString("export type CommandResult<\n")
	b.WriteString("  H extends HandlerName,\n")
	b.WriteString("  C extends CommandName<H>,\n")
	b.WriteString("> = LinuxIOSchema[H][C] extends { result: infer R } ? R : never;\n")
	return b.String()
}

func renderClient() string {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString("import { createEndpoint } from \"../react-query\";\n")
	b.WriteString("import type { TypedAPI } from \"../react-query\";\n\n")
	b.WriteString("const linuxio = {\n")
	byHandler := routesByHandler()
	handlers := sortedKeys(byHandler)
	for _, handler := range handlers {
		if !hasEndpoint(byHandler[handler]) {
			continue
		}
		fmt.Fprintf(&b, "  %s: {\n", handler)
		for _, route := range byHandler[handler] {
			if !route.Endpoint() {
				continue
			}
			fmt.Fprintf(&b, "    %s: createEndpoint(%q, %q),\n", route.Command(), route.Handler(), route.Command())
		}
		b.WriteString("  },\n")
	}
	b.WriteString("} as TypedAPI;\n\n")
	b.WriteString("export default linuxio;\n")
	return b.String()
}

func hasEndpoint(routes []apischema.RouteSpec) bool {
	for _, route := range routes {
		if route.Endpoint() {
			return true
		}
	}
	return false
}

func routesByHandler() map[string][]apischema.RouteSpec {
	byHandler := make(map[string][]apischema.RouteSpec)
	for _, route := range apischema.Routes {
		byHandler[route.Handler()] = append(byHandler[route.Handler()], route)
	}
	for handler := range byHandler {
		sort.Slice(byHandler[handler], func(i, j int) bool {
			return byHandler[handler][i].Command() < byHandler[handler][j].Command()
		})
	}
	return byHandler
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

var identifierRE = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_]*`)

func usedModelNames(modelNames []string) []string {
	modelSet := make(map[string]bool, len(modelNames))
	for _, name := range modelNames {
		modelSet[name] = true
	}

	used := make(map[string]bool)
	for _, route := range apischema.Routes {
		if !route.Endpoint() {
			continue
		}
		for _, token := range identifierRE.FindAllString(route.ArgsTS+" "+route.ResultTS, -1) {
			if modelSet[token] {
				used[token] = true
			}
		}
	}

	names := make([]string, 0, len(used))
	for name := range used {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

var exportNameRE = regexp.MustCompile(`(?m)^export\s+(?:interface|type|enum)\s+([A-Za-z_][A-Za-z0-9_]*)`)
var exportTypeListRE = regexp.MustCompile(`(?m)^export\s+type\s+\{([^}]+)\}`)

func exportedModelNames(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	matches := exportNameRE.FindAllSubmatch(data, -1)
	names := make([]string, 0, len(matches))
	seen := make(map[string]bool)
	for _, match := range matches {
		name := string(match[1])
		if !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	for _, match := range exportTypeListRE.FindAllSubmatch(data, -1) {
		for part := range strings.SplitSeq(string(match[1]), ",") {
			name := strings.TrimSpace(part)
			if before, _, ok := strings.Cut(name, " as "); ok {
				name = strings.TrimSpace(before)
			}
			if name == "" || seen[name] {
				continue
			}
			seen[name] = true
			names = append(names, name)
		}
	}
	sort.Strings(names)
	return names, nil
}
