package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/mordilloSan/LinuxIO/backend/bridge/apischema"
	"github.com/mordilloSan/LinuxIO/backend/bridge/handlers"
	bridgeipc "github.com/mordilloSan/LinuxIO/backend/common/ipc/bridge"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}
	outDir := filepath.Join(repoRoot, "frontend", "src", "api", "generated")
	if mkdirErr := os.MkdirAll(outDir, 0o755); mkdirErr != nil {
		fatal(mkdirErr)
	}

	generatedFiles := []string{
		filepath.Join(outDir, "route-metadata.ts"),
		filepath.Join(outDir, "linuxio-types.ts"),
		filepath.Join(outDir, "client.ts"),
	}

	if routeErr := writeFile(generatedFiles[0], renderRouteMetadata()); routeErr != nil {
		fatal(routeErr)
	}
	if typesErr := writeFile(generatedFiles[1], renderTypes()); typesErr != nil {
		fatal(typesErr)
	}
	if clientErr := writeFile(generatedFiles[2], renderClient()); clientErr != nil {
		fatal(clientErr)
	}
	if formatErr := formatGeneratedFiles(repoRoot, generatedFiles); formatErr != nil {
		fatal(formatErr)
	}
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, statErr := os.Stat(filepath.Join(dir, "frontend", "src", "api")); statErr == nil {
			return dir, nil
		}
		if parent := filepath.Dir(dir); parent == dir {
			return "", fmt.Errorf("could not find repo root from %s", wd)
		}
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "linuxio-api-gen:", err)
	os.Exit(1)
}

func writeFile(path string, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func formatGeneratedFiles(repoRoot string, paths []string) error {
	prettier := filepath.Join(repoRoot, "frontend", "node_modules", ".bin", "prettier")
	if _, err := os.Stat(prettier); err != nil {
		return nil
	}

	args := append([]string{"--log-level=error", "--write"}, paths...)
	cmd := exec.Command(prettier, args...)
	cmd.Dir = filepath.Join(repoRoot, "frontend")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("prettier failed: %w\n%s", err, out)
	}
	return nil
}

func header() string {
	return "// Code generated by linuxio-api-gen; DO NOT EDIT.\n\n"
}

func renderRouteMetadata() string {
	return renderRouteMetadataForRoutes(handlers.Routes)
}

func renderRouteMetadataForRoutes(routes []apischema.RouteSpec) string {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString("export type RouteMode = \"query\" | \"job\" | \"duplex\";\n\n")
	b.WriteString("export const ROUTE_MODES = {\n")
	for _, route := range routes {
		fmt.Fprintf(&b, "  %q: %q,\n", route.Route, string(route.Mode))
	}
	b.WriteString("} as const satisfies Record<string, RouteMode>;\n\n")
	b.WriteString("export function routeName(handler: string, command: string): string {\n")
	b.WriteString("  return `${handler}.${command}`;\n")
	b.WriteString("}\n\n")
	b.WriteString("export function getRouteMode(route: string): RouteMode | undefined {\n")
	b.WriteString("  return ROUTE_MODES[route as keyof typeof ROUTE_MODES];\n")
	b.WriteString("}\n")
	return b.String()
}

func renderTypes() string {
	return renderTypesForRoutes(handlers.Routes)
}

func renderTypesForRoutes(routes []apischema.RouteSpec) string {
	renderer := newTSRenderer()

	var schema strings.Builder
	schema.WriteString("export interface LinuxIOSchema {\n")
	byHandler := routesByHandler(routes)
	handlers := sortedKeys(byHandler)
	for _, handler := range handlers {
		if !hasEndpoint(byHandler[handler]) {
			continue
		}
		fmt.Fprintf(&schema, "  %s: {\n", handler)
		for _, route := range byHandler[handler] {
			if !route.Endpoint() {
				continue
			}
			fmt.Fprintf(
				&schema,
				"    %s: { input: %s; request: %s; result: %s };\n",
				route.Command(),
				renderer.inputTupleRef(route.RequestSpec()),
				renderer.requestRef(route.RequestSpec()),
				renderer.typeRef(route.ResultSpec()),
			)
		}
		schema.WriteString("  };\n\n")
	}
	schema.WriteString("}\n\n")
	schema.WriteString("/** Extract handler names from schema */\n")
	schema.WriteString("export type HandlerName = keyof LinuxIOSchema;\n\n")
	schema.WriteString("/** Extract command names for a given handler */\n")
	schema.WriteString("export type CommandName<H extends HandlerName> = keyof LinuxIOSchema[H];\n\n")
	schema.WriteString("/** Extract ergonomic input argument tuple for a handler/command pair */\n")
	schema.WriteString("export type CommandInput<\n")
	schema.WriteString("  H extends HandlerName,\n")
	schema.WriteString("  C extends CommandName<H>,\n")
	schema.WriteString("> = LinuxIOSchema[H][C] extends { input: infer I extends readonly unknown[] }\n")
	schema.WriteString("  ? I\n")
	schema.WriteString("  : never;\n\n")
	schema.WriteString("/** Extract request type for a handler/command pair */\n")
	schema.WriteString("export type CommandRequest<\n")
	schema.WriteString("  H extends HandlerName,\n")
	schema.WriteString("  C extends CommandName<H>,\n")
	schema.WriteString("> = LinuxIOSchema[H][C] extends { request: infer R } ? R : never;\n\n")
	schema.WriteString("/** Extract result type for a handler/command pair */\n")
	schema.WriteString("export type CommandResult<\n")
	schema.WriteString("  H extends HandlerName,\n")
	schema.WriteString("  C extends CommandName<H>,\n")
	schema.WriteString("> = LinuxIOSchema[H][C] extends { result: infer R } ? R : never;\n")

	for _, spec := range apischema.ExtraTypes {
		renderer.typeRef(spec)
	}
	definitions := renderer.definitions()

	var b strings.Builder
	b.WriteString(header())
	if definitions != "" {
		b.WriteString(definitions)
	}
	b.WriteString(schema.String())
	return b.String()
}

func renderClient() string {
	return renderClientForRoutes(handlers.Routes)
}

func renderClientForRoutes(routes []apischema.RouteSpec) string {
	var b strings.Builder
	b.WriteString(header())
	b.WriteString("import { createEndpoint } from \"../react-query\";\n")
	b.WriteString("import type { TypedAPI } from \"../react-query\";\n\n")
	b.WriteString("const linuxio = {\n")
	byHandler := routesByHandler(routes)
	handlers := sortedKeys(byHandler)
	for _, handler := range handlers {
		if !hasEndpoint(byHandler[handler]) {
			continue
		}
		fmt.Fprintf(&b, "  %s: {\n", handler)
		for _, route := range byHandler[handler] {
			if !route.Endpoint() {
				continue
			}
			fmt.Fprintf(
				&b,
				"    %s: createEndpoint(%q, %q, %s),\n",
				route.Command(),
				route.Handler(),
				route.Command(),
				requestShape(route.RequestSpec()),
			)
		}
		b.WriteString("  },\n")
	}
	b.WriteString("} as TypedAPI;\n\n")
	b.WriteString("export default linuxio;\n")
	return b.String()
}

func requestShape(request apischema.TypeSpec) string {
	if sameType(request.GoType, reflect.TypeFor[bridgeipc.NoRequest]()) {
		return `{ kind: "none" }`
	}
	if field, ok := scalarInputField(request.GoType); ok {
		name, _ := jsonFieldName(field)
		return fmt.Sprintf(`{ kind: "field", field: %q }`, name)
	}
	return `{ kind: "object" }`
}

func hasEndpoint(routes []apischema.RouteSpec) bool {
	for _, route := range routes {
		if route.Endpoint() {
			return true
		}
	}
	return false
}

func routesByHandler(routes []apischema.RouteSpec) map[string][]apischema.RouteSpec {
	byHandler := make(map[string][]apischema.RouteSpec)
	for _, route := range routes {
		byHandler[route.Handler()] = append(byHandler[route.Handler()], route)
	}
	for handler := range byHandler {
		sort.Slice(byHandler[handler], func(i, j int) bool {
			return byHandler[handler][i].Command() < byHandler[handler][j].Command()
		})
	}
	return byHandler
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

type tsRenderer struct {
	defs map[string]string
}

func newTSRenderer() *tsRenderer {
	return &tsRenderer{defs: make(map[string]string)}
}

func (r *tsRenderer) requestRef(request apischema.TypeSpec) string {
	if sameType(request.GoType, reflect.TypeFor[bridgeipc.NoRequest]()) {
		return "void"
	}
	return r.typeRef(request)
}

func (r *tsRenderer) inputTupleRef(request apischema.TypeSpec) string {
	if sameType(request.GoType, reflect.TypeFor[bridgeipc.NoRequest]()) {
		return "[]"
	}
	if field, ok := scalarInputField(request.GoType); ok {
		name, _ := jsonFieldName(field)
		return fmt.Sprintf("[%s: %s]", tsTupleLabel(name), r.reflectType(field.Type))
	}
	return fmt.Sprintf("[request: %s]", r.typeRef(request))
}

func (r *tsRenderer) typeRef(spec apischema.TypeSpec) string {
	return r.reflectType(spec.GoType)
}

func (r *tsRenderer) reflectType(t reflect.Type) string {
	t = deref(t)
	if t == nil {
		return "unknown"
	}
	if sameType(t, reflect.TypeFor[bridgeipc.NoResponse]()) {
		return "void"
	}
	if sameType(t, reflect.TypeFor[bridgeipc.NoRequest]()) {
		return "{}"
	}
	if t.PkgPath() == "time" && t.Name() == "Time" {
		return "string"
	}
	if t.PkgPath() != "" && t.Name() != "" && t.Kind() != reflect.Struct {
		r.addAlias(t)
		return t.Name()
	}

	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		return r.reflectType(t.Elem()) + "[]"
	case reflect.Map:
		key := r.reflectType(t.Key())
		if key != "string" && key != "number" {
			key = "string"
		}
		return fmt.Sprintf("Record<%s, %s>", key, r.reflectType(t.Elem()))
	case reflect.Struct:
		if t.Name() != "" {
			r.addDefinition(t)
			return t.Name()
		}
		return r.structLiteral(t)
	case reflect.Interface:
		return "unknown"
	default:
		return "unknown"
	}
}

func (r *tsRenderer) addDefinition(t reflect.Type) {
	t = deref(t)
	if t == nil || t.Kind() != reflect.Struct || t.Name() == "" {
		return
	}
	if _, exists := r.defs[t.Name()]; exists {
		return
	}
	r.defs[t.Name()] = ""
	r.defs[t.Name()] = fmt.Sprintf("export interface %s %s\n\n", t.Name(), r.structLiteral(t))
}

func (r *tsRenderer) addAlias(t reflect.Type) {
	t = deref(t)
	if t == nil || t.Name() == "" {
		return
	}
	if _, exists := r.defs[t.Name()]; exists {
		return
	}
	if values, ok := apischema.StringEnums[t.Name()]; ok && t.Kind() == reflect.String {
		quoted := make([]string, 0, len(values))
		for _, value := range values {
			quoted = append(quoted, fmt.Sprintf("%q", value))
		}
		r.defs[t.Name()] = fmt.Sprintf("export type %s = %s;\n\n", t.Name(), strings.Join(quoted, " | "))
		return
	}
	r.defs[t.Name()] = fmt.Sprintf("export type %s = %s;\n\n", t.Name(), r.unnamedType(t))
}

func (r *tsRenderer) unnamedType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		return r.reflectType(t.Elem()) + "[]"
	case reflect.Map:
		key := r.reflectType(t.Key())
		if key != "string" && key != "number" {
			key = "string"
		}
		return fmt.Sprintf("Record<%s, %s>", key, r.reflectType(t.Elem()))
	default:
		return "unknown"
	}
}

func (r *tsRenderer) structLiteral(t reflect.Type) string {
	var b strings.Builder
	b.WriteString("{\n")
	for _, field := range exportedJSONFields(t) {
		name, _ := jsonFieldName(field)
		optional := ""
		if jsonFieldOptional(field) {
			optional = "?"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", tsFieldName(name), optional, r.reflectType(field.Type))
	}
	b.WriteString("}")
	return b.String()
}

func (r *tsRenderer) definitions() string {
	if len(r.defs) == 0 {
		return ""
	}

	names := sortedKeys(r.defs)
	var b strings.Builder
	for _, name := range names {
		b.WriteString(r.defs[name])
	}
	return b.String()
}

func exportedJSONFields(t reflect.Type) []reflect.StructField {
	if t == nil || t.Kind() != reflect.Struct {
		return nil
	}

	fields := make([]reflect.StructField, 0, t.NumField())
	for field := range t.Fields() {
		if field.PkgPath != "" {
			continue
		}
		name, _ := jsonFieldName(field)
		if name == "-" {
			continue
		}
		if field.Anonymous && field.Tag.Get("json") == "" {
			fields = append(fields, exportedJSONFields(deref(field.Type))...)
			continue
		}
		fields = append(fields, field)
	}
	return fields
}

func jsonFieldName(field reflect.StructField) (string, []string) {
	tag := field.Tag.Get("json")
	if tag == "" {
		return lowerFirst(field.Name), nil
	}
	parts := strings.Split(tag, ",")
	if parts[0] == "" {
		parts[0] = lowerFirst(field.Name)
	}
	return parts[0], parts[1:]
}

func jsonFieldOptional(field reflect.StructField) bool {
	if field.Type.Kind() == reflect.Pointer {
		return true
	}
	_, opts := jsonFieldName(field)
	return slices.Contains(opts, "omitempty")
}

func scalarInputField(t reflect.Type) (reflect.StructField, bool) {
	t = deref(t)
	if t == nil || t.Kind() != reflect.Struct {
		return reflect.StructField{}, false
	}
	fields := exportedJSONFields(t)
	if len(fields) != 1 || jsonFieldOptional(fields[0]) {
		return reflect.StructField{}, false
	}
	return fields[0], true
}

func tsFieldName(name string) string {
	if tsIdentifierRE.MatchString(name) {
		return name
	}
	return fmt.Sprintf("%q", name)
}

func tsTupleLabel(name string) string {
	if tsIdentifierRE.MatchString(name) {
		return name
	}
	return "request"
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func deref(t reflect.Type) reflect.Type {
	for t != nil && t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

func sameType(a, b reflect.Type) bool {
	return a == deref(b)
}

var tsIdentifierRE = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)
