#!/bin/sh
# LinuxIO login banner - rendered into /run/motd.dynamic by pam_motd
# via the Debian/Ubuntu update-motd framework. Installed by LinuxIO.
if [ -r /run/linuxio/issue ]; then
    echo ""
    cat /run/linuxio/issue
    echo ""
fi
exit 0
