#!/bin/bash
set -e

# Automatically added by dh_systemd_start
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -d /run/systemd/system ]; then
        # Stop services before removal
        systemctl stop linuxio.target >/dev/null 2>&1 || true
        systemctl stop 'linuxio*' >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#

exit 0
