/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountsRouteRouteImport } from './routes/_authenticated/accounts/route'
import { Route as AuthenticatedDockerRouteRouteImport } from './routes/_authenticated/docker/route'
import { Route as AuthenticatedHardwareRouteRouteImport } from './routes/_authenticated/hardware/route'
import { Route as AuthenticatedLogsRouteRouteImport } from './routes/_authenticated/logs/route'
import { Route as AuthenticatedNetworkRouteRouteImport } from './routes/_authenticated/network/route'
import { Route as AuthenticatedServicesRouteRouteImport } from './routes/_authenticated/services/route'
import { Route as AuthenticatedSharesRouteRouteImport } from './routes/_authenticated/shares/route'
import { Route as AuthenticatedStorageRouteRouteImport } from './routes/_authenticated/storage/route'
import { Route as AuthenticatedTerminalRouteRouteImport } from './routes/_authenticated/terminal/route'
import { Route as AuthenticatedUpdatesRouteRouteImport } from './routes/_authenticated/updates/route'
import { Route as AuthenticatedVmRouteRouteImport } from './routes/_authenticated/vm/route'
import { Route as AuthenticatedWireguardRouteRouteImport } from './routes/_authenticated/wireguard/route'
import { Route as AuthenticatedFilebrowserSplatRouteImport } from './routes/_authenticated/filebrowser/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRouteRoute =
  AuthenticatedAccountsRouteRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDockerRouteRoute =
  AuthenticatedDockerRouteRouteImport.update({
    id: '/docker',
    path: '/docker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHardwareRouteRoute =
  AuthenticatedHardwareRouteRouteImport.update({
    id: '/hardware',
    path: '/hardware',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsRouteRoute = AuthenticatedLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworkRouteRoute =
  AuthenticatedNetworkRouteRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesRouteRoute =
  AuthenticatedServicesRouteRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSharesRouteRoute =
  AuthenticatedSharesRouteRouteImport.update({
    id: '/shares',
    path: '/shares',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageRouteRoute =
  AuthenticatedStorageRouteRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTerminalRouteRoute =
  AuthenticatedTerminalRouteRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUpdatesRouteRoute =
  AuthenticatedUpdatesRouteRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVmRouteRoute = AuthenticatedVmRouteRouteImport.update({
  id: '/vm',
  path: '/vm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWireguardRouteRoute =
  AuthenticatedWireguardRouteRouteImport.update({
    id: '/wireguard',
    path: '/wireguard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilebrowserSplatRoute =
  AuthenticatedFilebrowserSplatRouteImport.update({
    id: '/filebrowser/$',
    path: '/filebrowser/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounts': typeof AuthenticatedAccountsRouteRoute
  '/docker': typeof AuthenticatedDockerRouteRoute
  '/hardware': typeof AuthenticatedHardwareRouteRoute
  '/logs': typeof AuthenticatedLogsRouteRoute
  '/network': typeof AuthenticatedNetworkRouteRoute
  '/services': typeof AuthenticatedServicesRouteRoute
  '/shares': typeof AuthenticatedSharesRouteRoute
  '/storage': typeof AuthenticatedStorageRouteRoute
  '/terminal': typeof AuthenticatedTerminalRouteRoute
  '/updates': typeof AuthenticatedUpdatesRouteRoute
  '/vm': typeof AuthenticatedVmRouteRoute
  '/wireguard': typeof AuthenticatedWireguardRouteRoute
  '/filebrowser/$': typeof AuthenticatedFilebrowserSplatRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteRoute
  '/accounts': typeof AuthenticatedAccountsRouteRoute
  '/docker': typeof AuthenticatedDockerRouteRoute
  '/hardware': typeof AuthenticatedHardwareRouteRoute
  '/logs': typeof AuthenticatedLogsRouteRoute
  '/network': typeof AuthenticatedNetworkRouteRoute
  '/services': typeof AuthenticatedServicesRouteRoute
  '/shares': typeof AuthenticatedSharesRouteRoute
  '/storage': typeof AuthenticatedStorageRouteRoute
  '/terminal': typeof AuthenticatedTerminalRouteRoute
  '/updates': typeof AuthenticatedUpdatesRouteRoute
  '/vm': typeof AuthenticatedVmRouteRoute
  '/wireguard': typeof AuthenticatedWireguardRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/filebrowser/$': typeof AuthenticatedFilebrowserSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sign-in': typeof SignInRouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteRoute
  '/_authenticated/docker': typeof AuthenticatedDockerRouteRoute
  '/_authenticated/hardware': typeof AuthenticatedHardwareRouteRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRouteRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRouteRoute
  '/_authenticated/services': typeof AuthenticatedServicesRouteRoute
  '/_authenticated/shares': typeof AuthenticatedSharesRouteRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRouteRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRouteRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRouteRoute
  '/_authenticated/vm': typeof AuthenticatedVmRouteRoute
  '/_authenticated/wireguard': typeof AuthenticatedWireguardRouteRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/filebrowser/$': typeof AuthenticatedFilebrowserSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/'
    | '/accounts'
    | '/docker'
    | '/hardware'
    | '/logs'
    | '/network'
    | '/services'
    | '/shares'
    | '/storage'
    | '/terminal'
    | '/updates'
    | '/vm'
    | '/wireguard'
    | '/filebrowser/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/accounts'
    | '/docker'
    | '/hardware'
    | '/logs'
    | '/network'
    | '/services'
    | '/shares'
    | '/storage'
    | '/terminal'
    | '/updates'
    | '/vm'
    | '/wireguard'
    | '/'
    | '/filebrowser/$'
  id:
    | '__root__'
    | '/sign-in'
    | '/_authenticated'
    | '/_authenticated/accounts'
    | '/_authenticated/docker'
    | '/_authenticated/hardware'
    | '/_authenticated/logs'
    | '/_authenticated/network'
    | '/_authenticated/services'
    | '/_authenticated/shares'
    | '/_authenticated/storage'
    | '/_authenticated/terminal'
    | '/_authenticated/updates'
    | '/_authenticated/vm'
    | '/_authenticated/wireguard'
    | '/_authenticated/'
    | '/_authenticated/filebrowser/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignInRouteRoute: typeof SignInRouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docker': {
      id: '/_authenticated/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof AuthenticatedDockerRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hardware': {
      id: '/_authenticated/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AuthenticatedHardwareRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shares': {
      id: '/_authenticated/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof AuthenticatedSharesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vm': {
      id: '/_authenticated/vm'
      path: '/vm'
      fullPath: '/vm'
      preLoaderRoute: typeof AuthenticatedVmRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wireguard': {
      id: '/_authenticated/wireguard'
      path: '/wireguard'
      fullPath: '/wireguard'
      preLoaderRoute: typeof AuthenticatedWireguardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filebrowser/$': {
      id: '/_authenticated/filebrowser/$'
      path: '/filebrowser/$'
      fullPath: '/filebrowser/$'
      preLoaderRoute: typeof AuthenticatedFilebrowserSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRouteRoute: typeof AuthenticatedAccountsRouteRoute
  AuthenticatedDockerRouteRoute: typeof AuthenticatedDockerRouteRoute
  AuthenticatedHardwareRouteRoute: typeof AuthenticatedHardwareRouteRoute
  AuthenticatedLogsRouteRoute: typeof AuthenticatedLogsRouteRoute
  AuthenticatedNetworkRouteRoute: typeof AuthenticatedNetworkRouteRoute
  AuthenticatedServicesRouteRoute: typeof AuthenticatedServicesRouteRoute
  AuthenticatedSharesRouteRoute: typeof AuthenticatedSharesRouteRoute
  AuthenticatedStorageRouteRoute: typeof AuthenticatedStorageRouteRoute
  AuthenticatedTerminalRouteRoute: typeof AuthenticatedTerminalRouteRoute
  AuthenticatedUpdatesRouteRoute: typeof AuthenticatedUpdatesRouteRoute
  AuthenticatedVmRouteRoute: typeof AuthenticatedVmRouteRoute
  AuthenticatedWireguardRouteRoute: typeof AuthenticatedWireguardRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFilebrowserSplatRoute: typeof AuthenticatedFilebrowserSplatRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRouteRoute: AuthenticatedAccountsRouteRoute,
  AuthenticatedDockerRouteRoute: AuthenticatedDockerRouteRoute,
  AuthenticatedHardwareRouteRoute: AuthenticatedHardwareRouteRoute,
  AuthenticatedLogsRouteRoute: AuthenticatedLogsRouteRoute,
  AuthenticatedNetworkRouteRoute: AuthenticatedNetworkRouteRoute,
  AuthenticatedServicesRouteRoute: AuthenticatedServicesRouteRoute,
  AuthenticatedSharesRouteRoute: AuthenticatedSharesRouteRoute,
  AuthenticatedStorageRouteRoute: AuthenticatedStorageRouteRoute,
  AuthenticatedTerminalRouteRoute: AuthenticatedTerminalRouteRoute,
  AuthenticatedUpdatesRouteRoute: AuthenticatedUpdatesRouteRoute,
  AuthenticatedVmRouteRoute: AuthenticatedVmRouteRoute,
  AuthenticatedWireguardRouteRoute: AuthenticatedWireguardRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFilebrowserSplatRoute: AuthenticatedFilebrowserSplatRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SignInRouteRoute: SignInRouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
